### ISSUE TITLE
Model Hashes (Some names found via joint name) Exported from Blood Of The Dead

### ISSUE THREAD

**Issue by SpSSdy** [Scobalula/GreyhoundPackageIndex#1]
`xmodel_21c0b4305bd98f9,p8_zm_esc_watchtower_frame
xmodel_21c0c4305bd9aac,p8_zm_esc_watchtower_platform
xmodel_21c0d4305bd9c5f,p8_zm_esc_watchtower_windows
xmodel_21c0e4305bd9e12,p8_zm_esc_watchtower_roof
xmodel_226f184b0cdfbc0,p8_mp_global_killconfirmed_dogtags
xmodel_22b522e250c9e7f,p8_zm_esc_jaildoor_01
xmodel_22bc018037432b0,p8_zm_esc_banjo_01
xmodel_2109b86cfc8469,p8_zm_esc_jaildoor_02
xmodel_1e769079f0c5268,p8_zm_esc_book_pile_01
xmodel_1c6d010275b54aa,p8_zm_esc_jail_door_outer_01
xmodel_1c6cf10275b52f7,p8_zm_esc_jail_door_frame_01
xmodel_1c52f97a54821f1,p8_zm_esc_chyo_chamber
xmodel_1aabdf6cc13ebee,p8_zm_esc_sml_desk_01
xmodel_187f9f275e94c64,p8_zm_esc_warden_helmet
xmodel_16e3a2b5397bf39,p8_zm_esc_skull_pile_01
xmodel_166ad9a37535d57,p8_zm_esc_dinghy_01
xmodel_15a04ae27c497aa,p8_zm_esc_house_vista_destroyed_interior_01
xmodel_1403dfd7aeda049,p8_zm_esc_electric_generator_01
xmodel_12ffdb460266366,p8_zm_esc_electric_generator_animated_01
xmodel_119677529b8f3fa,p8_zm_esc_skull_single_01
xmodel_1184621ba691c9d,p8_zm_esc_brickwall_destroyed_01
xmodel_1116b08a4be5200,p8_zm_esc_generator_big_01
xmodel_107cbf3ad4d0a06,p8_zm_esc_lava_crystal_01
xmodel_14a3d89844265ef,p8_zm_esc_sheet_metal_4x8_bd_07
xmodel_9294536a43cd524,p8_zm_esc_chimney_ladder_01
xmodel_1c9ea5745c63150,p8_zm_esc_machinery_01
xmodel_1c73317d78e85b2,p8_zm_esc_door_frame_01
xmodel_188f6dbc069e4dc,p8_zm_esc_light_bulb_vintage_00
xmodel_187f9f275e94c64,p8_zm_esc_warden_helmet
xmodel_19effa699d77e75,p8_zm_esc_lightbulb_vintage_02
xmodel_19bcbcc345bcda5,p8_zm_esc_shelf_wall_01
xmodel_197b75095b7e86e,p8_zm_esc_light_alarm_01
xmodel_19584d2080db8ae,p8_zm_esc_barrel_metal_01
xmodel_18f65ccd1f7885,p8_zm_esc_open_window_small_01
xmodel_21c367aa50b03d6,p8_zm_esc_wooden_table_rustic_01
xmodel_2274f81dbd4485d,p8_zm_esc_brick_entrance_frame_01
xmodel_2362b8557a12260,p8_zm_esc_railing_concrete_01
xmodel_233332d098bb622,p8_zm_esc_destroyed_pipe_01
xmodel_22b522e250c9e7f,p8_zm_esc_jaildoor_bars_01
xmodel_22a91a492006d84,p8_zm_esc_spike_grid_trap_01
xmodel_1eb00e7f82d89ea,p8_zm_esc_light_bulb_01
xmodel_1e9ed7394b94a0c,p8_zm_esc_doorframe_fancy_01
xmodel_20ba7990d9f47be,p8_zm_esc_window_1x2_01
xmodel_20445360da31091,p8_zm_esc_barrel_drum_pallet
xmodel_bf833a86c5204e0,p8_zm_esc_concrete_pillar_block_03
xmodel_b9face5c7e40724,p8_zm_esc_wooden_crate_01
xmodel_c76ab0f4fdc2dfe,p8_zm_esc_barrel_wood_01
xmodel_b580cc822af6ea1,p8_zm_esc_shelf_metal_wood_01
xmodel_b43adc7a08d64d3,p8_zm_esc_metal_shutters_01
xmodel_b35a04ba2ed49e2,p8_zm_esc_flower_vase_flowers_02
xmodel_a31862a14b9b958,p8_zm_esc_foliage_disticis_hanging_ledge_32_long
xmodel_a444ee33918b91a,p8_zm_esc_wrench_metal_01
xmodel_b2d572ab1f29b3d,p8_zm_esc_window_interior_01
xmodel_ac8044621f28acf,p8_zm_esc_flower_vase_01
xmodel_a679a5b5bfb8c0f,p8_zm_esc_jail_door_small_01
xmodel_15abd49d36eb4b9,p8_zm_esc_spot_light_01
xmodel_159cf95028a05e5,p8_zm_esc_window_thin_01
xmodel_159ce95028a0432,p8_zm_esc_double_window_roof_01
xmodel_158fcefdb16607a,p8_zm_esc_broom
xmodel_1548575bb97bded,p8_zm_esc_concrete_lamp_01
xmodel_17546ab0fe3bf48,p8_zm_esc_electrical_box_thin_01
xmodel_1745465004d3218,p8_zm_esc_wooden_floor_01
xmodel_16fe14f1630c08e,p8_zm_esc_food_fruit_apple_cap_dmg
xmodel_167d57b4d013be1,p8_fxp_wood_splinter_01
xmodel_152e861f104692d,p8_zm_esc_armchair_fancy_01
xmodel_14b5c3d18222857,p8_zm_esc_wooden_chair_01
xmodel_13021a880db2150,p8_ice_rock_wall_02_b
xmodel_11cb60ac5cb4a9e,p8_rock_wall_22_v3_game_mesh
xmodel_11cb50ac5cb48eb,p8_basalt_wall_cliff_22_slice_02_low_poly_01
xmodel_1443d8c38f29b4b,p7_zm_zod_boxer_gym_ibeam_64_01
xmodel_6e89f6489511436,p8_zm_esc_warden_organs_spider_0
xmodel_6e5ba3b86126ebc,p8_zm_esc_destroyed_wood_crate_01
xmodel_6dda24f4d119c4d,p8_zm_esc_house_extended_foundation_01
xmodel_7062c3bf62bb039,p8_zm_esc_window_frame_01
xmodel_6f35bb48ae20ed3,p8_zm_esc_cliff_rock_01
xmodel_6bb24cc41f969e0,p8_zm_esc_railing_concrete_destroyed_01
xmodel_6ac08b6d3fd85da,p8_zm_esc_barbed_wire_01
xmodel_6aba717d0f4843e,p8_zm_esc_paper_pile_01
xmodel_6c60b635de706,p7_pipe_metal_hp_4_t_joint
xmodel_6d27c7f9fbddaf5,p8_zm_esc_computer_machinery_01
xmodel_6d1ecfe530aff2d,p8_zm_esc_wheel_front_right_spokes1

`

**Comment by Black-DeathZM** [comment]
a bit slow are we

**Comment by Black-DeathZM** [comment]
Please remove the xmodel_ prefix from your hashes next time. Added.
