### ISSUE TITLE
More CW Marshal Models [Hash Verified] [xModels]

### ISSUE THREAD

**Issue by BeefyQuads** [Scobalula/GreyhoundPackageIndex#136]
169e2effd3ff5bd,wpn_t9_loot_pistol_shotgun_clip_view
a626cba2c5a8c00,wpn_t9_loot_pistol_shotgun_clip_world
394c89c59925a12,wpn_t9_loot_pistol_shotgun_le_view
12ba7d8863b3325,wpn_t9_loot_pistol_shotgun_le_world
6b56a9cd22a4303,wpn_t9_loot_pistol_shotgun_le_clip_view
1c74935a228ee56,wpn_t9_loot_pistol_shotgun_le_clip_world

**Comment by ItsNatoriousB** [comment]
NICE!

**Comment by ItsNatoriousB** [comment]
Make sure you include ``` from the template
