### ISSUE TITLE
CW Season Two Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#26]
Naga
dc62add06807f6e,c_t9_lao_pl_serpent_arms
c627c24d532c3da,c_t9_lao_pl_serpent_arms_viewbody
d2c0f569b7f8997,c_t9_lao_pl_serpent_viewarms
580486e38965839,c_t9_lao_pl_serpent_viewlegs
61d5ca1c3dac867,c_t9_lao_pl_serpent_head
7c9f1c6d124368a,c_t9_lao_pl_serpent_lowerbody
6cfbae4dedd31e,c_t9_lao_pl_serpent_lowerbody_viewbody
f87a2b7a6c5e5a8,c_t9_lao_pl_serpent_torso
45199579b6e9ad4,c_t9_lao_pl_serpent_torso_viewbody
52415bf6eb544f8,c_t9_lao_pl_serpent_warlord_arms
e300ba3984fb2504,c_t9_lao_pl_serpent_warlord_arms_viewbody
e7ade74f51927f9,c_t9_lao_pl_serpent_warlord_viewarms
d6c5308c9d21a8b,c_t9_lao_pl_serpent_warlord_viewlegs
b94cf83a33a0dc1,c_t9_lao_pl_serpent_warlord_head
1321d4773773404,c_t9_lao_pl_serpent_warlord_lowerbody
3228fd142bc5318,c_t9_lao_pl_serpent_warlord_lowerbody_viewbody
66c847c38597226,c_t9_lao_pl_serpent_warlord_torso
22c5ed887254fa2,c_t9_lao_pl_serpent_warlord_torso_viewbody

Park
c8f427728d0b8a2,c_t9_uk_pl_mi6_survivor_arms
63729076cb72886,c_t9_uk_pl_mi6_survivor_arms_viewbody
9b24e4cc47de6a3,c_t9_uk_pl_mi6_survivor_viewarms
779ef22c2d3df35,c_t9_uk_pl_mi6_survivor_viewlegs
4c0e4c396e76173,c_t9_uk_pl_mi6_survivor_head
431746cfcaf63ee,c_t9_uk_pl_mi6_survivor_lowerbody
7ddff349f40b95a,c_t9_uk_pl_mi6_survivor_lowerbody_viewbody
298833dafaba3d4,c_t9_uk_pl_mi6_survivor_torso
48172e727c98008,c_t9_uk_pl_mi6_survivor_torso_viewbody

Sims
b2d3054bd28985a,c_t9_usa_pl_cia_commando_arms
6aca70607a177ce,c_t9_usa_pl_cia_commando_arms_viewbody
e8c404fa797b36b,c_t9_usa_pl_cia_commando_viewarms
327e1ae17eec85d,c_t9_usa_pl_cia_commando_viewlegs
c33f219518bfe0b,c_t9_usa_pl_cia_commando_head
dfc89fec09644a6,c_t9_usa_pl_cia_commando_lowerbody
76e4d3bb6efef22,c_t9_usa_pl_cia_commando_lowerbody_viewbody
d7d4a37feda2d2c,c_t9_usa_pl_cia_commando_torso
75d24c16916bc50,c_t9_usa_pl_cia_commando_torso_viewbody

Adler
54082c74258fde2,c_t9_usa_pl_adler_renegade_arms
b1cc18746f813c6,c_t9_usa_pl_adler_renegade_arms_viewbody
b8cf78b189f07e3,c_t9_usa_pl_adler_renegade_viewarms
954986116f50075,c_t9_usa_pl_adler_renegade_viewlegs
3f7250ec870fbb3,c_t9_usa_pl_adler_renegade_head
3bffe92b958da2e,c_t9_usa_pl_adler_renegade_lowerbody
8064fe4a615069a,c_t9_usa_pl_adler_renegade_lowerbody_viewbody
8c78302df5f0e14,c_t9_usa_pl_adler_renegade_torso
69b140744df0848,c_t9_usa_pl_adler_renegade_torso_viewbody

Woods
29ed2ec99567451,c_t9_usa_pl_woods_pow_arms
df369a5da288ccb,c_t9_usa_pl_woods_pow_arms_viewbody
9bdfc3fdae7016c,c_t9_usa_pl_woods_pow_viewarms
33ff69f18b55f6,c_t9_usa_pl_woods_pow_viewlegs
3eb59288e250f20,c_t9_usa_pl_woods_pow_head
8c1f31a3f6ae9e3,c_t9_usa_pl_woods_pow_lowerbody
291f3468d2b85d,c_t9_usa_pl_woods_pow_lowerbody_viewbody
1644932369186f5,c_t9_usa_pl_woods_pow_torso
6d5bc64c6700b77,c_t9_usa_pl_woods_pow_torso_viewbody

Garcia
c7709cb0151cfd5,c_t9_cub_pl_dgi_havana_arms
69494b4ebda5c17,c_t9_cub_pl_dgi_havana_arms_viewbody
b58476a8d134ff8,c_t9_cub_pl_dgi_havana_viewarms
1397252673f3eb2,c_t9_cub_pl_dgi_havana_viewlegs
fc750062ee6a19c,c_t9_cub_pl_dgi_havana_head
58736ec0beb1cd7,c_t9_cub_pl_dgi_havana_lowerbody
2e332e63ee26769,c_t9_cub_pl_dgi_havana_lowerbody_viewbody
f2eb1a3ad99e541,c_t9_cub_pl_dgi_havana_torso
3b2e8bdb9a5b11b,c_t9_cub_pl_dgi_havana_torso_viewbody
dad91886fd60ffd,c_t9_cub_pl_dgi_brawler_arms
cd9b4a64ec1ed2f,c_t9_cub_pl_dgi_brawler_arms_viewbody
8852ec2ad2b6a50,c_t9_cub_pl_dgi_brawler_viewarms
15b9a2eaeb63b4a,c_t9_cub_pl_dgi_brawler_viewlegs
3a4b74013683a04,c_t9_cub_pl_dgi_brawler_head
1cfa5815c66fe5f,c_t9_cub_pl_dgi_brawler_lowerbody
5406e606492b5a1,c_t9_cub_pl_dgi_brawler_lowerbody_viewbody
31d887511585909,c_t9_cub_pl_dgi_brawler_torso
c63950ca86f08f3,c_t9_cub_pl_dgi_brawler_torso_viewbody

**Comment by ItsNatoriousB** [comment]
Shoutout to RipleyGames with the MAJOR assist on finding these

**Comment by EthanC** [comment]
Thank you
