### ISSUE TITLE
CW Season Two Weapons (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#27]
6ae7fddc67705f6,wpn_t9_loot_ar_slowhandling_view
621e52ced2d1e52,wpn_t9_loot_ar_slowhandling_mag_view
6e7f44286fabe6e,wpn_t9_loot_smg_accurate_view
8820573848d8c2a,wpn_t9_loot_smg_accurate_mag_view
15b8ce667e93e1b,wpn_t9_melee_machete_view
14817511aea2077,wpn_t9_melee_shovel_view

**Comment by ItsNatoriousB** [comment]
Shoutout to steviewonder87 for finding these!

**Comment by EthanC** [comment]
Thank you
