### ISSUE TITLE
Model Hashes (Miscellaneous)

### ISSUE THREAD

**Issue by Faithfullfaun** [Scobalula/GreyhoundPackageIndex#3]
116b2db875f5136,wpn_t8_vapr_vampire_hunter_world
151be8b99a3200e,veh_civ_hotrod
16d35d9569f268e,wpn_t8_saug_9mm_great_lion_view
fed341e5a6f3278,attach_t8_sight_threat_world
fbc6dcda727164d,c_t8_firebreak_operator_robber_head
fba98e0e25aad10,wpn_t8_purifier_world
fabcbbbf8f160b7,wpn_t8_war_machine_view
fb6857485335d2d,wpn_t8_ballistic_shield_open_view
fb248727440f82b,wpn_t8_paladin_valkyrie_view
f9f52f1da2b26b0,wpn_t8_ballistic_shield_world
faa5a42e84493e0,c_t8_outrider_operator_head2
fa8ef4b99808ac5,c_t8_battery_operator_body
dfed8696070c9c2,c_t8_prophet_operator_body
f9e8b7b90cd41d6,wpn_t8_tempest_view
b5d787798f9014d,c_t8_raven_full
ed6ede84d4c2b6c,c_t8_ruin_operator_body
263003aff8da24c,c_t8_robot_torso
3aedfb0eafdcddf,c_t8_robot_torso2
795d969e6d83601,c_t8_robot_body
356970e33767836,c_t8_robot_torso_cut_l_arm
ff6638576fc7d6b,veh_air_gunship
566dbd92baeff09,veh_air_gunship2
61a3fffa36d816d,veh_air_gunship3
b99c9349fef019c,veh_air_drone_squad_body
4cb8e69c1c3b674,veh_air_drone_squad_body2
18c211a107deb7e,c_t8_ruin_operator_head
5793278078b7b66,c_t8_outrider_operator_head
3e672897d271610,c_t8_zom_godfrey_head
6c132274af0b6d1,c_t8_zom_jonathan_warwick_head
25b44e86ac09ad6,c_t8_firebreak_operator_cop_head
2a4f99676684a3d,c_t8_zom_john_doe_legs
1df6b1e5f4f8822,c_t8_ruin_operator_robber_legs
7b22978ccfb7fe4,c_t8_ruin_operator_cop_legs
7f89b3dccbbde58,c_t8_nomad_operator_robber_head
61d6523ef5db0ac,c_t8_ruin_operator_cop_head
1addfea85516f7,c_t8_zero_operator_knight_torso
49d8a9590730768,c_t8_zero_operator_knight_torso2
e896e0f7f50a8db,c_t8_zero_operator_torso
44529c58fc3fe70,c_t8_outrider_operator_torso
d4570cdff4f5a07,c_t8_outrider_operator_torso2
79f65b50bb27176,c_t8_outrider_operator_torso3
4ada7e92dc3836d,c_t8_outrider_operator_torso4
1a6f40934470f8f,c_t8_nomad_operator_cop_head
14b49f9608bc853,wpn_t8_auger_dmr_zx7000_world
4aec36d767ce436,c_t8_zom_warden_head
3becf684bd2dc0d,c_t8_zero_operator_head
1260c276a1f907f,wpn_t8_kn57_kuromaku_world
dc033fc5487fb40,c_t8_zero_operator_head2
e8d2cabe6ffce57,C_t8_ruin_operator_robber_torso
d0d0780a3d51838,wpn_t8_auger_dmr_zx7000_view
d0716da4bfe84d4,wpn_t8_sparrow_view
a2b7ffcc665af3f,wpn_t8_bomb_world
a3f2f44806d96ac,c_t8_firebreak_operator_robber_torso
6682761b342bf07,c_t8_ruin_operator_robber_head
806237643421be,c_t8_ruin_operator_cop_torso
326a992e398a2f2,c_t8_outrider_operator_legs
2e4c8d519540447,c_t8_hudson_vacation_torso
63137cd5d27ccf6,c_t8_nomad_operator_robber_legs_cut
4fd00da0bc33d2a,c_t8_firebreak_operator_robber_legs

**Comment by Scobalula** [comment]
These will be pushed in the next update to Greyhound. Thanks!
