### ISSUE TITLE
More Season Two Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#31]
dfa5f819c405ac8,c_t9_usa_pl_woods_rogue_head
57b9cebcf380f9,c_t9_usa_pl_woods_rogue_arms
e0e2857b5332583,c_t9_usa_pl_woods_rogue_arms_viewbody
fed34f6d0a05524,c_t9_usa_pl_woods_rogue_viewarms
5a4379d5a5f0f4e,c_t9_usa_pl_woods_rogue_viewlegs
b5601fb96eb577d,c_t9_usa_pl_woods_rogue_torso
2befe63ab0b3baf,c_t9_usa_pl_woods_rogue_torso_viewbody
43d513eff9a548b,c_t9_usa_pl_woods_rogue_lowerbody
bd1607897744ef5,c_t9_usa_pl_woods_rogue_lowerbody_viewbody
70ec2e56667b17,c_t9_cub_pl_dgi_commando_head
9e3fa6a332a5b1e,c_t9_cub_pl_dgi_commando_arms
44ad377d214abea,c_t9_cub_pl_dgi_commando_arms_viewbody
d119c9f6bd4da87,c_t9_cub_pl_dgi_commando_viewarms
a93f5b7a5e95ec9,c_t9_cub_pl_dgi_commando_viewlegs
635b0ea82bcf518,c_t9_cub_pl_dgi_commando_torso
24e6ad0eec0b9e4,c_t9_cub_pl_dgi_commando_torso_viewbody
d9cf8749044ed7a,c_t9_cub_pl_dgi_commando_lowerbody
c66016a681f192e,c_t9_cub_pl_dgi_commando_lowerbody_viewbody
b0f3cd7d8b1caa5,c_t9_usa_pl_navyseal_hunter_head
2ece3132ce49cd4,c_t9_usa_pl_navyseal_hunter_arms
40d6f4dfc49fb08,c_t9_usa_pl_navyseal_hunter_arms_viewbody
740f318582e481d,c_t9_usa_pl_navyseal_hunter_viewarms
bf63fef065ed2bf,c_t9_usa_pl_navyseal_hunter_viewlegs
5ae069eeb0d29fa,c_t9_usa_pl_navyseal_hunter_torso
f119bb9f41e96ae,c_t9_usa_pl_navyseal_hunter_torso_viewbody
bc75be3079aac90,c_t9_usa_pl_navyseal_hunter_lowerbody
7808cca86565c4c,c_t9_usa_pl_navyseal_hunter_lowerbody_viewbody
e93ee4461547a03,c_t9_uk_pl_mi6_clandestine_head
d3a0bfc40666272,c_t9_uk_pl_mi6_clandestine_arms
b3692ced1e438f6,c_t9_uk_pl_mi6_clandestine_arms_viewbody
bd8275fdae8833,c_t9_uk_pl_mi6_clandestine_viewarms
201434c979254e5,c_t9_uk_pl_mi6_clandestine_viewlegs
259be68630e0724,c_t9_uk_pl_mi6_clandestine_torso
de6cf30444a2a78,c_t9_uk_pl_mi6_clandestine_torso_viewbody
36c3339c4279fe,c_t9_uk_pl_mi6_clandestine_lowerbody
e4f4ad8cfc4820a,c_t9_uk_pl_mi6_clandestine_lowerbody_viewbody

Shatter Blast
dabd96b7684e947,attach_t9_ammo_mod_shatter_blast_view

**Comment by EthanC** [comment]
Thanks
