### ISSUE TITLE
Black Ops 3 Russian Hash Sounds [Hash Verified] [xsound]

### ISSUE THREAD

**Issue by CuBnIcK** [Scobalula/GreyhoundPackageIndex#325]
[bo3_sab_ru.csv](https://github.com/Scobalula/GreyhoundPackageIndex/files/7918896/bo3_sab_ru.csv)

**Comment by YuRaNnNzZZ** [comment]
найди работу чел

**Comment by CuBnIcK** [comment]
ладно бро
