### ISSUE TITLE
CW UI Images (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#34]
939a448f945d099,ui_icon_mtx_tileimage_operator_mi6_survivor_v0
939a348f95cee6,ui_icon_mtx_tileimage_operator_mi6_survivor_v1
939a248f945cd33,ui_icon_mtx_tileimage_operator_mi6_survivor_v2
381178222deecdc,ui_icon_mtx_tileimage_operator_mi6_glam_v0
1a85b0f31f887a0,ui_icon_mtx_tileimage_operator_mi6_racer_v0
c298b17deacfddc,ui_icon_mtx_tileimage_operator_mi6_napalm_v0
9890bf57248cdbd,ui_icon_mtx_tileimage_operator_adler_bloodhound_v0
9890af57248cc0a,ui_icon_mtx_tileimage_operator_adler_bloodhound_v1
98909f57248ca57,ui_icon_mtx_tileimage_operator_adler_bloodhound_v2
a9e5abe2994d7b4,ui_icon_mtx_tileimage_operator_adler_gator_v0
e4c1954c326d73a,ui_icon_mtx_tileimage_operator_adler_renegade_v0
1b7994e95b8794,ui_icon_mtx_tileimage_operator_adler_wire_v0
c7274ba713ed88c,ui_icon_mtx_tileimage_operator_adler_tropic_v0
44357ec72d58a02,ui_icon_mtx_tileimage_operator_adler_red_v0
931c5d5585c379d,ui_icon_mtx_tileimage_operator_adler_gamefuel_v0
d79163f7f5aa10,ui_icon_mtx_tileimage_operator_adler_vice_v0
2d04d46a4f5307f,ui_icon_mtx_tileimage_operator_woods_pow_v0
375f128cd3f09b1,ui_icon_mtx_tileimage_operator_woods_swamp_v0
411d2d5e895b19d,ui_icon_mtx_tileimage_operator_woods_eliminator_v0
295beba245ffbf6,ui_icon_mtx_tileimage_operator_seal_breaker_v0
3321ffb57678825,ui_icon_mtx_tileimage_operator_seal_sniper_v0
10ccf0b5cd81875,ui_icon_mtx_tileimage_operator_seal_ringleader_v0
9b02a1f15a43430,ui_icon_mtx_tileimage_operator_seal_gigawatt_v0
d54d7cca69446ef,ui_icon_mtx_tileimage_operator_cia_urgentfury_v0
e20f3e7caf7cb4f,ui_icon_mtx_tileimage_operator_cia_sogman_v0
15c2e948793c72e,ui_icon_mtx_tileimage_operator_wgerman_police_v0
4df8f444110b6d,ui_icon_mtx_tileimage_operator_wgerman_swat_v0
6743b4220d2e445,ui_icon_mtx_tileimage_operator_wgerman_paratrooper_v0
868615030c2c9b5,ui_icon_mtx_tileimage_operator_maxis_dark_v0
2ffd6b170764c27,ui_icon_mtx_tileimage_operator_kgb_shadow_v0
b6bf8ca5c1a16ae,ui_icon_mtx_tileimage_operator_kgb_gunshow_v0
7a61c30e8a00c08,ui_icon_mtx_tileimage_operator_kgb_thekid_v0
b9443d9840d28e3,ui_icon_mtx_tileimage_operator_kgb_punk_v0
bbe1ea484ce892f,ui_icon_mtx_tileimage_operator_serpent_v0
bbe1da484ce877c,ui_icon_mtx_tileimage_operator_serpent_v1
bbe20a484ce8c95,ui_icon_mtx_tileimage_operator_serpent_v2
bbe1fa484ce8ae2,ui_icon_mtx_tileimage_operator_serpent_v3
ebfee02dd1cf3bd,ui_icon_mtx_tileimage_operator_serpent_warlord_v0
ebfed02dd1cf20a,ui_icon_mtx_tileimage_operator_serpent_warlord_v1
ebfec02dd1cf057,ui_icon_mtx_tileimage_operator_serpent_warlord_v2
54a9e08489e89cd,ui_icon_mtx_tileimage_operator_cuban_brawler_v0
19e624dc79348c4,ui_icon_mtx_tileimage_operator_cuban_general_v0
8978904f626b4d7,ui_icon_mtx_tileimage_operator_cuban_havana_v0
98488e5a272947,ui_icon_mtx_tileimage_operator_cuban_warlord_v0
3f2b6d451acfb42,ui_icon_mtx_tileimage_operator_starter3_stone_siege_v0
3f2b7d451acfcf5,ui_icon_mtx_tileimage_operator_starter3_stone_siege_v1
3f2b4d451acf7dc,ui_icon_mtx_tileimage_operator_starter3_stone_siege_v2
72267327b8b257e,ui_icon_mtx_tileimage_operator_stitch_cultist_v0
4cfa1e56f1bf7a5,ui_icon_mtx_tileimage_operator_starter1_hunter_rescue_v0
4cfa0e56f1bf5f2,ui_icon_mtx_tileimage_operator_starter1_hunter_rescue_v1
4cf9fe56f1bf43f,ui_icon_mtx_tileimage_operator_starter1_hunter_rescue_v2
684cecb9e7f57bb,ui_icon_mtx_tileimage_operator_starter5_dust_v0
684cdcb9e7f5608,ui_icon_mtx_tileimage_operator_starter5_dust_v1
684d0cb9e7f5b21,ui_icon_mtx_tileimage_operator_starter5_dust_v2
db004d0fb2c5ec2,ui_icon_mtx_tileimage_operator_starter4_counter_v0
db005d0fb2c6075,ui_icon_mtx_tileimage_operator_starter4_counter_v1
db002d0fb2c5b5c,ui_icon_mtx_tileimage_operator_starter4_counter_v2
39d61275bf44985,ui_icon_mtx_tileimage_operator_starter2_steel_v0
702521ced5c6eac,ui_icon_mtx_tileimage_operator_bulldozer_toxin_v0

**Comment by EthanC** [comment]
Thanks
