### ISSUE TITLE
CW More Models (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#35]
b8de3211d5d03b5,p9_field_up_gas_mine
2ff934513bac879,p9_field_up_prox_mine
c936e15bcdf935a,p9_field_up_fld_mic
6af2d2b590fc093,p9_field_up_asslt_pack
b29791291da097,p9_field_up_barricade

**Comment by EthanC** [comment]
Thanks
