### ISSUE TITLE
Even More Models (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#36]
Operators
d113e85c402034f,c_t9_usa_pl_deltaforce_jungle_warfare_head
3fa0c3d79c06cf6,c_t9_usa_pl_deltaforce_jungle_warfare_arms
759b9922c9b0252,c_t9_usa_pl_deltaforce_jungle_warfare_arms_viewbody
62979c885f8a3d0,c_t9_usa_pl_deltaforce_jungle_warfare_torso
34df25a275da78c,c_t9_usa_pl_deltaforce_jungle_warfare_torso_viewbody
dd9d559ac3a8f52,c_t9_usa_pl_deltaforce_jungle_warfare_lowerbody
b8dc55684f77596,c_t9_usa_pl_deltaforce_jungle_warfare_lowerbody_viewbody
1a394a1f0ba722f,c_t9_usa_pl_deltaforce_jungle_warfare_viewarms
f400d369ea18331,c_t9_usa_pl_deltaforce_jungle_warfare_viewlegs
d56e12198884aca,c_t9_nic_pl_smuggler_head
810b36ea15e2a73,c_t9_nic_pl_smuggler_arms
a3e153d3fb94ecd,c_t9_nic_pl_smuggler_arms_viewbody
7e167a54da453e3,c_t9_nic_pl_smuggler_torso
869a70366f1965d,c_t9_nic_pl_smuggler_torso_viewbody
c48d7eeb01f11bd,c_t9_nic_pl_smuggler_lowerbody
caf2ef9dbaa3eef,c_t9_nic_pl_smuggler_lowerbody_viewbody
3e16c0c62561d9e,c_t9_nic_pl_smuggler_viewarms
9b6faf42b185c38,c_t9_nic_pl_smuggler_viewlegs
f6e31b87ae22901,c_t9_rus_pl_kgb_bunny_head
f8277ef5e5eb538,c_t9_rus_pl_kgb_bunny_arms
825d2ccb0aa244,c_t9_rus_pl_kgb_bunny_arms_viewbody
f6e2441c3003b66,c_t9_rus_pl_kgb_bunny_torso
1ccbdcd99c569e2,c_t9_rus_pl_kgb_bunny_torso_viewbody
abc640d7e3cfc44,c_t9_rus_pl_kgb_bunny_lowerbody
3503599e7263458,c_t9_rus_pl_kgb_bunny_lowerbody_viewbody
587844a5dac2a39,c_t9_rus_pl_kgb_bunny_viewarms
477f8de326369cb,c_t9_rus_pl_kgb_bunny_viewlegs

Zombies
9b775e292672631,wpn_t9_zm_wand_cannister_frenzied_guard_view
886ddfc9fd579e4,wpn_t9_zm_wand_frenzied_guard_world
2fe6c53009d3811,wpn_t9_zm_wand_frenzied_guard_view
6976dd18a2b9195,wpn_t9_zm_perk_can_quick_revive_world

Charms
892cbf27ccb2511,attach_t9_charm_sneaker_optic_sy
8cfd1f27cfedd61,attach_t9_charm_sneaker_optic_ms
88fe9f27cc92234,attach_t9_charm_sneaker_optic_pc
a4bbb05d4704f91,attach_t9_charm_aztec_god
91added5979a70a,attach_t9_charm_bomber_hat
d3f839c354adead,attach_t9_charm_btomahawk
c0b4b2500f0b8ce,attach_t9_charm_bug_zapper
8fd8bc589d9e494,attach_t9_charm_bullet_collision
dc3f5d787ccc19f,attach_t9_charm_burger_town
e2dfa3413f897a0,attach_t9_charm_dummy_head
168f1f22710cd54,attach_t9_charm_saphdeity
ab4fb5012aedbdd,attach_t9_charm_gas_mask
6cfbd0eee7acc01,attach_t9_charm_gator_teeth
ddc3e8223211737,attach_t9_charm_hotel_room_key
288f821c81a5a3f,attach_t9_charm_mill_dollar_chip
3fb870a0bc57a22,attach_t9_charm_moon
4025860606e0b9b,attach_t9_charm_multi_tool
8914ecd4accecf9,attach_t9_charm_objective_marker
8eb8c99275f782b,attach_t9_charm_pot_o_gold
42268c76372dad7,attach_t9_charm_caesar_ring
7c4ab7c7b88660c,attach_t9_charm_russian_medal
2abdae4e02518f3,attach_t9_charm_scythe
185eb3995b53094,attach_t9_charm_silver_badger
35ce8593d1485d5,attach_t9_charm_vietn_helmet
c70bd8d441fbd82,attach_t9_charm_tiki_totem
6cc7f3b9981330e,attach_t9_charm_eaglemullet
5b9ade297546b3b,attach_t9_charm_heartbreaker
4964676e0e4ee9d,attach_t9_charm_hellscream
b7db9f3234ec7d6,attach_t9_charm_spinning_rim
37dcefbaf1cca04,attach_t9_charm_madcloud
ddf4a8afde2ca40,attach_t9_charm_metalpeace
b6059b38b6f4c48,attach_t9_charm_bleach
4a6a04f56a5cf6a,attach_t9_charm_methane_molecule
13defa760189f42,attach_t9_charm_pilothelmet
4c424e9f3e9762d,attach_t9_charm_zombiefoot
9307ed68b246d3e,attach_t9_charm_artillery_gun
49074249886e5fa,attach_t9_charm_aboot
4d19e3b3a9a7fe6,attach_t9_charm_bfetish
3b646886c4d8fa8,attach_t9_charm_gold_card
72a6365129d8aea,attach_t9_charm_zombie_bunny
d2f79858bcd849f,attach_t9_charm_canteen
eb7b48d5b931067,attach_t9_charm_electricghost
e864b85d5763269,attach_t9_charm_e_tool
e0788b5c1221fa9,attach_t9_charm_fake_ppt
4ad7fbfb6164272,attach_t9_charm_jousting_horse
c14b5e17da77363,attach_t9_charm_parachute_soldier
c1e8ebb4daa624f,attach_t9_charm_steelskull
576b8c9c15da6b8,attach_t9_charm_sniper_tent
95a4a5eb1ba9ff7,attach_t9_charm_marr_male
fc6e3a6f10775d,attach_t9_charm_prison_shiv
1fe69e8066cf1e6,attach_t9_charm_redacted_doc
e7439219e64f275,attach_t9_charm_g_gnome_lep
fde3ccf92d1399e,attach_t9_charm_dragon_claw
4abadfc7075a8b4,attach_t9_charm_jungle_trap

**Comment by EthanC** [comment]
Thanks
