### ISSUE TITLE
More Season Two Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#37]
Beck
f3866855ae6dadb,c_t9_ger_pl_west_carnage_head
82964c028cbe56a,c_t9_ger_pl_west_carnage_arms
185cae0d5b8883e,c_t9_ger_pl_west_carnage_arms_viewbody
39b6cdcbdf384fc,c_t9_ger_pl_west_carnage_torso
1bc66a5dbf6bbc0,c_t9_ger_pl_west_carnage_torso_viewbody
243cb1afe9f99f6,c_t9_ger_pl_west_carnage_lowerbody
7530ef690695952,c_t9_ger_pl_west_carnage_lowerbody_viewbody
3a551a11d383abb,c_t9_ger_pl_west_carnage_viewarms
4cf12fb4349b10d,c_t9_ger_pl_west_carnage_viewlegs

Stone
709cff7ac432228,c_t9_gen_pl_starter3_stone_stoned_head
c862a3fe2147459,c_t9_gen_pl_starter3_stone_stoned_arms
f5a5c804a11da3,c_t9_gen_pl_starter3_stone_stoned_arms_viewbody
9deba93e3a5e15d,c_t9_gen_pl_starter3_stone_stoned_torso
18283752ce5a94f,c_t9_gen_pl_starter3_stone_stoned_torso_viewbody
967b16773a67f6b,c_t9_gen_pl_starter3_stone_stoned_lowerbody
181816519984815,c_t9_gen_pl_starter3_stone_stoned_lowerbody_viewbody
5c3183c3ba5c884,c_t9_gen_pl_starter3_stone_stoned_viewarms
1fe1adddd6424ae,c_t9_gen_pl_starter3_stone_stoned_viewlegs

Portnova
c2c69fe9fa45c38,c_t9_rus_pl_kgb_ghost_head
7b10447732d3e29,c_t9_rus_pl_kgb_ghost_arms
e3ab91d9b010d53,c_t9_rus_pl_kgb_ghost_arms_viewbody
d4fbf159dd8222d,c_t9_rus_pl_kgb_ghost_torso
c7ed667ce0257bf,c_t9_rus_pl_kgb_ghost_torso_viewbody
d9f6c23c43d62fb,c_t9_rus_pl_kgb_ghost_lowerbody
126297f0e01f385,c_t9_rus_pl_kgb_ghost_lowerbody_viewbody
692505373ef4294,c_t9_rus_pl_kgb_ghost_viewarms
bec32f4773e549e,c_t9_rus_pl_kgb_ghost_viewlegs

Bulldozer
29ebd34a4182ae0,c_t9_usa_pl_bulldozer_hawk_head
4b836f8b22cb911,c_t9_usa_pl_bulldozer_hawk_arms
11cac24e8b0348b,c_t9_usa_pl_bulldozer_hawk_arms_viewbody
f5389bb82aa87b5,c_t9_usa_pl_bulldozer_hawk_torso
7cd2f72566cb337,c_t9_usa_pl_bulldozer_hawk_torso_viewbody
a7bd4ca62b154a3,c_t9_usa_pl_bulldozer_hawk_lowerbody
85e3a00a874a11d,c_t9_usa_pl_bulldozer_hawk_lowerbody_viewbody
feecaa35d12ba2c,c_t9_usa_pl_bulldozer_hawk_viewarms
665cdcd73b8c1b6,c_t9_usa_pl_bulldozer_hawk_viewlegs

**Comment by EthanC** [comment]
Thanks
