### ISSUE TITLE
Season Three Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#42]
Adler
7c87bb64fd3353b,c_t9_usa_pl_adler_hostage_head
d5279f11ad363ca,c_t9_usa_pl_adler_hostage_arms
5171e43a71d915e,c_t9_usa_pl_adler_hostage_arms_viewbody
34f0f080392d7dc,c_t9_usa_pl_adler_hostage_torso
d0478b9ebfbdf60,c_t9_usa_pl_adler_hostage_torso_viewbody
69e56177098d3d6,c_t9_usa_pl_adler_hostage_lowerbody
949687381f7a5f2,c_t9_usa_pl_adler_hostage_lowerbody_viewbody
3170c1dd8138e1b,c_t9_usa_pl_adler_hostage_viewarms
440cd77fe25046d,c_t9_usa_pl_adler_hostage_viewlegs

Beck
32859cc197ee229,c_t9_ger_pl_west_klown_head
2109f7f6fb90220,c_t9_ger_pl_west_klown_arms
7201ed212a1c1fc,c_t9_ger_pl_west_klown_arms_viewbody
19458c9ddbb1ae,c_t9_ger_pl_west_klown_torso
75f9ad1f9e0051a,c_t9_ger_pl_west_klown_torso_viewbody
9c96fc29e3c042c,c_t9_ger_pl_west_klown_lowerbody
f8daf5a97f3b150,c_t9_ger_pl_west_klown_lowerbody_viewbody
71a0c63940b2171,c_t9_ger_pl_west_klown_viewarms
96d817b907f5b63,c_t9_ger_pl_west_klown_viewlegs

Garcia
d0071ac89696b8f,c_t9_cub_pl_dgi_slasher_head
a6f3f5f572add36,c_t9_cub_pl_dgi_slasher_arms
111ea009bd03592,c_t9_cub_pl_dgi_slasher_arms_viewbody
10524a9f4adef10,c_t9_cub_pl_dgi_slasher_torso
d303e6a1ab4bcc,c_t9_cub_pl_dgi_slasher_torso_viewbody
143275dbbed5392,c_t9_cub_pl_dgi_slasher_lowerbody
54780054c9353d6,c_t9_cub_pl_dgi_slasher_lowerbody_viewbody
9818851ea04676f,c_t9_cub_pl_dgi_slasher_viewarms
71e00e697eb7871,c_t9_cub_pl_dgi_slasher_viewlegs

Hunter
22e5996b71bd98b,c_t9_gen_pl_starter1_hunter_inferno_head
12797d222b873da,c_t9_gen_pl_starter1_hunter_inferno_arms
3ff55dcd93bc24e,c_t9_gen_pl_starter1_hunter_inferno_arms_viewbody
5d6a44b924c27ac,c_t9_gen_pl_starter1_hunter_inferno_torso
526bbc7924353d0,c_t9_gen_pl_starter1_hunter_inferno_torso_viewbody
132941cd49b2726,c_t9_gen_pl_starter1_hunter_inferno_lowerbody_viewbody
9cf9b1625f3bea2,c_t9_gen_pl_starter1_hunter_inferno_lowerbody_viewbody
16e2b7144c506eb,c_t9_gen_pl_starter1_hunter_inferno_viewarms
609cccfb51c1bdd,c_t9_gen_pl_starter1_hunter_inferno_viewlegs
a5ddb93037afd39,c_t9_gen_pl_starter1_hunter_frontline_head
33c2145bbfa9430,c_t9_gen_pl_starter1_hunter_frontline_arms
9de3b1993c87d2c,c_t9_gen_pl_starter1_hunter_frontline_arms_viewbody
2dd61f207132ffe,c_t9_gen_pl_starter1_hunter_frontline_torso
7c51664c826040a,c_t9_gen_pl_starter1_hunter_frontline_torso_viewbody
80e89845347087c,c_t9_gen_pl_starter1_hunter_frontline_lowerbody
ff4f2574c867e40,c_t9_gen_pl_starter1_hunter_frontline_lowerbody_viewbody
c6a1203b625ba01,c_t9_gen_pl_starter1_hunter_frontline_viewarms
752a71c527c8593,c_t9_gen_pl_starter1_hunter_frontline_viewlegs

Knight
3df96381408fe64,c_t9_uk_pl_sas_blackknight_head
76470855877325d,c_t9_uk_pl_sas_blackknight_arms
3fdc060b644ac4f,c_t9_uk_pl_sas_blackknight_arms_viewbody
b5107de25699de9,c_t9_uk_pl_sas_blackknight_torso
5f0270ed7208c13,c_t9_uk_pl_sas_blackknight_torso_viewbody
41f193f84da6c3f,c_t9_uk_pl_sas_blackknight_lowerbody
e6fcc3855b765c1,c_t9_uk_pl_sas_blackknight_lowerbody_viewbody
c4d311189e5b4b0,c_t9_uk_pl_sas_blackknight_viewarms
88a9c7d8e5561aa,c_t9_uk_pl_sas_blackknight_viewlegs

Park
e2e9c82f737b0aa,c_t9_uk_pl_mi6_dystopia_head
2d36ecb1af20e53,c_t9_uk_pl_mi6_dystopia_arms
6c0310c0203e76d,c_t9_uk_pl_mi6_dystopia_arms_viewbody
4a9e5c7e3f0f643,c_t9_uk_pl_mi6_dystopia_torso
d49cdd4c11ac7d,c_t9_uk_pl_mi6_dystopia_torso_viewbody
9dba166bbea671d,c_t9_uk_pl_mi6_dystopia_lowerbody
75311d2680cfa0f,c_t9_uk_pl_mi6_dystopia_lowerbody_viewbody
135c75bf205a47e,c_t9_uk_pl_mi6_dystopia_viewarms
a2a563ecfe60f18,c_t9_uk_pl_mi6_dystopia_viewlegs
b916047edd091e0,c_t9_uk_pl_mi6_coal_head
daada0bfbe52011,c_t9_uk_pl_mi6_coal_arms
c3caee48a59d98b,c_t9_uk_pl_mi6_coal_arms_viewbody
c05a381c7018cb5,c_t9_uk_pl_mi6_coal_torso
8d6db1209b01237,c_t9_uk_pl_mi6_coal_torso_viewbody
35f91f908a729a3,c_t9_uk_pl_mi6_coal_lowerbody
b196df75661701d,c_t9_uk_pl_mi6_coal_lowerbody_viewbody
7d8c07add29112c,c_t9_uk_pl_mi6_coal_viewarms
e4fc3a4f3cf18b6,c_t9_uk_pl_mi6_coal_viewlegs

Portnova
a3fbcc9d3402e0f,c_t9_rus_pl_kgb_funnybone_head
7ae8a7ca1019fb6,c_t9_rus_pl_kgb_funnybone_arms
7da5e4476a7a512,c_t9_rus_pl_kgb_funnybone_arms_viewbody
a54476e6c9a6e90,c_t9_rus_pl_kgb_funnybone_torso
ee013337dbdc24c,c_t9_rus_pl_kgb_funnybone_torso_viewbody
fa26382bc038b12,c_t9_rus_pl_kgb_funnybone_lowerbody
ff313cd0a8e7256,c_t9_rus_pl_kgb_funnybone_lowerbody_viewbody
3c718efb7fe91ef,c_t9_rus_pl_kgb_funnybone_viewarms
163918465e5a2f1,c_t9_rus_pl_kgb_funnybone_viewlegs

Price
647bd63f109096a,c_t9_uk_pl_price_arms_viewbody
76d670987fb9a64,c_t9_uk_pl_price_torso_viewbody
50af29be9d641ae,c_t9_uk_pl_price_lowerbody_viewbody

Song
cd0108dfdaf33f9,c_t9_gen_pl_starter4_song_bloom_head
2905645a11251f0,c_t9_gen_pl_starter4_song_bloom_arms
e445ac5ee4d86ec,c_t9_gen_pl_starter4_song_bloom_arms_viewbody
c05a86e18aee5be,c_t9_gen_pl_starter4_song_bloom_torso
cd6a03cc7df32ca,c_t9_gen_pl_starter4_song_bloom_torso_viewbody
e3baf8f51dae73c,c_t9_gen_pl_starter4_song_bloom_lowerbody
b2a4e9c3e1ae100,c_t9_gen_pl_starter4_song_bloom_lowerbody_viewbody
68d9fddfd23e9c1,c_t9_gen_pl_starter4_song_bloom_viewarms
17734f6997c6853,c_t9_gen_pl_starter4_song_bloom_viewlegs

Woods
6e0db1a5d44fb3c,c_t9_usa_pl_woods_whirlwind_head
39094df2fb02975,c_t9_usa_pl_woods_whirlwind_arms
c00ac7e74dd1af7,c_t9_usa_pl_woods_whirlwind_arms_viewbody
76a64f35fea6e61,c_t9_usa_pl_woods_whirlwind_torso
3a1dcb52e181e7b,c_t9_usa_pl_woods_whirlwind_torso_viewbody
7d3364a91a64af7,c_t9_usa_pl_woods_whirlwind_lowerbody
c02c8a03182f2c9,c_t9_usa_pl_woods_whirlwind_lowerbody_viewbody
2ca294725748198,c_t9_usa_pl_woods_whirlwind_viewarms
8ac542effa22352,c_t9_usa_pl_woods_whirlwind_viewlegs

Wolf
45b0e9673b97006,c_t9_usa_pl_deltaforce_dynamite_head
d70505b31b4fd37,c_t9_usa_pl_deltaforce_dynamite_arms
90cf351dc4cc709,c_t9_usa_pl_deltaforce_dynamite_arms_viewbody
be80996bf489c7f,c_t9_usa_pl_deltaforce_dynamite_torso
c92c854f8e61101,c_t9_usa_pl_deltaforce_dynamite_torso_viewbody
54b1e3181a4d0f1,c_t9_usa_pl_deltaforce_dynamite_lowerbody
75608127e77edab,c_t9_usa_pl_deltaforce_dynamite_lowerbody_viewbody
e917a95db57f96a,c_t9_usa_pl_deltaforce_dynamite_viewarms
64ae13767e24944,c_t9_usa_pl_deltaforce_dynamite_viewlegs

Wraith
916394ebb93178a,c_t9_fin_pl_wraith_head
dba0b96df4bc233,c_t9_fin_pl_wraith_arms
3ac418d74f6338d,c_t9_fin_pl_wraith_arms_viewbody
7a074068b4131a3,c_t9_fin_pl_wraith_torso
761b5c0db80081d,c_t9_fin_pl_wraith_torso_viewbody
4b7fea6f92787d,c_t9_fin_pl_wraith_lowerbody
b95cbec3328aeaf,c_t9_fin_pl_wraith_lowerbody_viewbody
3f0a5096676615e,c_t9_fin_pl_wraith_viewarms
66033f12c5576f8,c_t9_fin_pl_wraith_viewlegs
5ca5638bc7a40e3,c_t9_fin_pl_wraith_white_queen_head
79073ebb0ac0852,c_t9_fin_pl_wraith_white_queen_arms
34a15a8ada97096,c_t9_fin_pl_wraith_white_queen_arms_viewbody
cf9829f47228b84,c_t9_fin_pl_wraith_white_queen_torso
fd227e54188d198,c_t9_fin_pl_wraith_white_queen_torso_viewbody
73a6e8d5dd5d95e,c_t9_fin_pl_wraith_white_queen_lowerbody
2936fe7e1df6a2a,c_t9_fin_pl_wraith_white_queen_lowerbody_viewbody
ef33fb10c403b13,c_t9_fin_pl_wraith_white_queen_viewarms
370087a62407c5,c_t9_fin_pl_wraith_white_queen_viewlegs

Zeyna
990f405d824e3b6,c_t9_fra_pl_dgse_mademoiselle_head
8af35cb33d946e7,c_t9_fra_pl_dgse_mademoiselle_arms
7adf8d069519ad9,c_t9_fra_pl_dgse_mademoiselle_arms_viewbody
2441706001e65af,c_t9_fra_pl_dgse_mademoiselle_torso
7bef698f414291,c_t9_fra_pl_dgse_mademoiselle_torso_viewbody
253dd7255719fe1,c_t9_fra_pl_dgse_mademoiselle_lowerbody
39e258317b1cafb,c_t9_fra_pl_dgse_mademoiselle_lowerbody_viewbody
8c912eef694215a,c_t9_fra_pl_dgse_mademoiselle_viewarms
3f55994cd65c2d4,c_t9_fra_pl_dgse_mademoiselle_viewlegs

**Comment by EthanC** [comment]
Thanks
