### ISSUE TITLE
CW UI Images (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#44]
679e586a6ce677b,ui_icon_mtx_tileimage_operator_woods_whirlwind_v0
5dcbb345791d034,ui_icon_mtx_tileimage_operator_adler_hostage_v0
2207aa1fbb39b3c,ui_icon_mtx_tileimage_operator_wolf_dynamite_v0
4271035173a7e39,ui_icon_mtx_tileimage_operator_smuggler
73973a3c778b19d,ui_icon_mtx_tileimage_operator_wraith_v0
73972a3c778afea,ui_icon_mtx_tileimage_operator_wraith_v1
73971a3c778ae37,ui_icon_mtx_tileimage_operator_wraith_v2
73970a3c778ac84,ui_icon_mtx_tileimage_operator_wraith_v3
7396fa3c778aad1,ui_icon_mtx_tileimage_operator_wraith_v4
8099c439a642a04,ui_icon_mtx_tileimage_operator_mi6_dystopia_v0
2af9a7a311e175e,ui_icon_mtx_tileimage_operator_mi6_coal_v0
2af9b7a311e1911,ui_icon_mtx_tileimage_operator_mi6_coal_v1
2af987a311e13f8,ui_icon_mtx_tileimage_operator_mi6_coal_v2
2af997a311e15ab,ui_icon_mtx_tileimage_operator_mi6_coal_v3
69e03d6c7f537e5,ui_icon_mtx_tileimage_operator_bulldozer_hawk_v0
af1eaa9bc4fd253,ui_icon_mtx_tileimage_operator_bulldozer_boom_v0
3d2db6611d5bcbe,ui_icon_mtx_tileimage_operator_kgb_ghost_v0
c6d6309867cf81a,ui_icon_mtx_tileimage_operator_cia_macv
8f0de153d14ca19,ui_icon_mtx_tileimage_operator_starter1_hunter_inferno_v0
75df9bc5242643b,ui_icon_mtx_tileimage_operator_starter1_hunter_frontline_v0
c28b6d9a60983,ui_icon_mtx_tileimage_operator_starter4_song_bloom_v0
3c480b0aaee33f5,ui_icon_mtx_tileimage_operator_wgerman_klown_v0

**Comment by Scobalula** [comment]
Thanks!
