### ISSUE TITLE
More Season Three Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#45]
Bulldozer
25045a58dcc9da6,c_t9_usa_pl_bulldozer_boom_head
b65876a4bc82ad7,c_t9_usa_pl_bulldozer_boom_arms
18ecab5d3be7169,c_t9_usa_pl_bulldozer_boom_arms_viewbody
6c2f8400de0699f,c_t9_usa_pl_bulldozer_boom_torso
33d0c06a658a3e1,c_t9_usa_pl_bulldozer_boom_torso_viewbody
a5355837cf92411,c_t9_usa_pl_bulldozer_boom_lowerbody
17f5b26c2ae258b,c_t9_usa_pl_bulldozer_boom_lowerbody_viewbody
444c0bee5475f0a,c_t9_usa_pl_bulldozer_boom_viewarms
bfe276071d1aee4,c_t9_usa_pl_bulldozer_boom_viewlegs

Vargas
e00756de1a4a4b4,c_t9_gen_pl_starter2_vargas_finishline_head
5670fb5a33e13ed,c_t9_gen_pl_starter2_vargas_finishline_arms
e4f409fa9fdfe7f,c_t9_gen_pl_starter2_vargas_finishline_arms_viewbody
3a816d1926726f9,c_t9_gen_pl_starter2_vargas_finishline_torso
aa25a348a4c7783,c_t9_gen_pl_starter2_vargas_finishline_torso_viewbody
7b822669ba3c2cf,c_t9_gen_pl_starter2_vargas_finishline_lowerbody
7474bf192296671,c_t9_gen_pl_starter2_vargas_finishline_lowerbody_viewbody
fa41afe7dfd59c0,c_t9_gen_pl_starter2_vargas_finishline_viewarms
6b26669e56d9e1a,c_t9_gen_pl_starter2_vargas_finishline_viewlegs
9cdb77e648aa544,c_t9_gen_pl_starter2_vargas_bunker_head
b891cbabdc023d,c_t9_gen_pl_starter2_vargas_bunker_arms
28add7ac6cb186f,c_t9_gen_pl_starter2_vargas_bunker_arms_viewbody
6aeb25dd6d26849,c_t9_gen_pl_starter2_vargas_bunker_torso
9453ffa5ea0f633,c_t9_gen_pl_starter2_vargas_bunker_torso_viewbody
2365e3d01cef09f,c_t9_gen_pl_starter2_vargas_bunker_lowerbody
e795ebd2cc6a8e1,c_t9_gen_pl_starter2_vargas_bunker_lowerbody_viewbody
fefc79e0c5d1d90,c_t9_gen_pl_starter2_vargas_bunker_viewarms
c2d330a10ccca8a,c_t9_gen_pl_starter2_vargas_bunker_viewlegs

**Comment by Scobalula** [comment]
Thanks!
