### ISSUE TITLE
CW Weapon Animations (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#47]
Combat Knife
6ff426e05a8cbbb,vm_combat_knife_ads_base_down
4bc469969eed3fb,vm_combat_knife_t9_ads_base_down
57ec3a31f1b121a,vm_combat_knife_ads_base_up
8f43620699ede5a,vm_combat_knife_t9_ads_base_up
b23427c9ca765ed,vm_combat_knife_t9_active_idle
47f5c0f0371ac2a,vm_combat_knife_crawl_b
225b225514c066a,vm_combat_knife_t9_crawl_b
47f580f0371a55e,vm_combat_knife_crawl_f
225ae25514bff9e,vm_combat_knife_t9_crawl_f
47f4e0f03719460,vm_combat_knife_crawl_l
225a425514beea0,vm_combat_knife_t9_crawl_l
47f6c0f0371c75a,vm_combat_knife_crawl_r
225c225514c219a,vm_combat_knife_t9_crawl_r
5f6d382da0d40c3,vm_combat_knife_crawl_in
1f5db6924157503,vm_combat_knife_t9_crawl_in
d80c65879fe9830,vm_combat_knife_crawl_out
80ff2a845f03a70,vm_combat_knife_t9_crawl_out
e13db21c286f1cd,vm_combat_knife_first_raise
e67e5a291c6ae0d,vm_combat_knife_t9_first_raise
b4a23d2a42e9762,vm_combat_knife_t9_idle
4d576a2aed6a6a4,vm_combat_knife_t9_inspect
15ec37c89a0aa7c,vm_combat_knife_jump
26b2608b1bee2c,vm_combat_knife_t9_melee
364563aef69b501,vm_combat_knife_t9_pullout
8378363868e539f,vm_combat_knife_t9_putaway
5193d20165965d2,vm_combat_knife_sprint_in
c5c6a2498f3bc12,vm_combat_knife_t9_sprint_in
6d10dd1635c5fdf,vm_combat_knife_sprint_loop
af2488dd39e351f,vm_combat_knife_t9_sprint_loop
64987861685498b,vm_combat_knife_sprint_out
7c4c63002c4fecb,vm_combat_knife_t9_sprint_out
9cc9965637a6bb6,vm_combat_knife_t9_sprint_pullout
ca88ac24d41f4e8,vm_combat_knife_t9_sprint_putaway

Crossbow
18d33892f4daf9b,vm_crossbow_t9_active_idle
33f6834ec5c99ed,vm_crossbow_t9_ads_down
f105b45dfab5881,vm_crossbow_t9_ads_fire
f56173d53d1b0de,vm_crossbow_t9_ads_fire_last
a59d64cf1ea82b8,vm_crossbow_t9_ads_up
4ebe8d3f262c4ca,vm_crossbow_t9_ads_elo_down
74eec205ce4ac6f,vm_crossbow_t9_ads_elo_up
ce0b017d16d7c44,vm_crossbow_t9_ads_reflex_down
e290a8f5c5e68c5,vm_crossbow_t9_ads_reflex_up
9ce27d8f45d59a0,vm_crossbow_t9_crawl_b
9ce2bd8f45d606c,vm_crossbow_t9_crawl_f
9ce35d8f45d716a,vm_crossbow_t9_crawl_l
9ce37d8f45d74d0,vm_crossbow_t9_crawl_r
6cca5a73abeef0d,vm_crossbow_t9_crawl_in
e623828dc9436d6,vm_crossbow_t9_crawl_out
ce976b4c7546c6a,vm_crossbow_t9_fire
4addbc432d5514f,vm_crossbow_t9_fire_last
d32a940198cbcdf,vm_crossbow_t9_first_raise
c4acaf3f35fc7ec,vm_crossbow_t9_gunbutt_swipe
d0758319593b320,vm_crossbow_t9_idle
505a9d0e032d38a,vm_crossbow_t9_inspect
81ef872f5325c5f,vm_crossbow_t9_pullout
ff3f454345d81c7,vm_crossbow_t9_pullout_quick
7d946c937cbe86d,vm_crossbow_t9_putaway
f809074d744c1b9,vm_crossbow_t9_putaway_quick
7a157cfcdb1bbcb,vm_crossbow_t9_reload
6bc832fc28fbefe,vm_crossbow_t9_reload_ads
21e8083dd6e5acd,vm_crossbow_t9_reload_empty
acf68251e772870,vm_crossbow_t9_reload_empty_ads
98e6b462db8e28,vm_crossbow_t9_sprint_in
a8f4b6d5f3b3bf9,vm_crossbow_t9_sprint_loop
143b884055f784d,vm_crossbow_t9_sprint_out
35d9e057fd7b68,vm_crossbow_t9_sprint_pullout
415a2af5d34b362,vm_crossbow_t9_sprint_putaway

E-Tool
ae4553875dc75a8,vm_etool_t9_ads_base_down
a2464598263b721,vm_etool_t9_ads_base_up
1a55eaafa12bd9,vm_etool_t9_crawl_b
1a59eaafa132a5,vm_etool_t9_crawl_f
1a5feaafa13cd7,vm_etool_t9_crawl_l
1a65eaafa14709,vm_etool_t9_crawl_r
dfcb2c86eebb7c2,vm_etool_t9_crawl_in
615849499ad11db,vm_etool_t9_crawl_out
fff794a7142c4c2,vm_etool_t9_first_raise
842ca667ffaa0a7,vm_etool_t9_idle
cb72b95234f3ed3,vm_etool_t9_inspect
93c286da830fcf7,vm_etool_t9_melee
f080d71363e4916,vm_etool_t9_pullout
868fec938072748,vm_etool_t9_putaway
a444c4d77e10845,vm_etool_t9_sprint_in
6c4308ed76a8648,vm_etool_t9_sprint_loop
56e3ca2be0ecf2e,vm_etool_t9_sprint_out
af0bafa76bb2dab,vm_etool_t9_sprint_pullout
5457bc0355a5ac1,vm_etool_t9_sprint_putaway

Machete
2fa9d1748613f90,vm_machete_t9_active_idle
e0ca2022b3ecac,vm_machete_t9_ads_down
9f8f7bd5e00866d,vm_machete_t9_ads_up
2e9c45d82cf82b3,vm_machete_t9_crawl_b
2e9c85d82cf897f,vm_machete_t9_crawl_f
2e9d25d82cf9a7d,vm_machete_t9_crawl_l
2e9d45d82cf9de3,vm_machete_t9_crawl_r
2d985e546b457b0,vm_machete_t9_crawl_in
da4a0972e8e7195,vm_machete_t9_crawl_out
b664c36565d34a8,vm_machete_t9_first_raise
dccca21c4edb7e9,vm_machete_t9_idle
748d7b4cf8d387d,vm_machete_t9_inspect
fd00681b747dba5,vm_machete_t9_melee
2f485d2ea6bfe80,vm_machete_t9_pullout
61abe955b0e2f7a,vm_machete_t9_putaway
d5e554a1700d0e7,vm_machete_t9_sprint_in
ac7b45c7530c476,vm_machete_t9_sprint_loop
a656fe53264cdec,vm_machete_t9_sprint_out
b8d2f296d511199,vm_machete_t9_sprint_pullout
83404fc7421c8d7,vm_machete_t9_sprint_putaway

PPSh
5f63c0512b583b6,vm_smg_spray_t9_ads_acog_up
354e454b8025bff,vm_smg_spray_t9_ads_acog_down
8c0c36ec84a9a26,vm_smg_spray_t9_ads_base_down
cfee0d870ae76d3,vm_smg_spray_t9_ads_base_up
38d1c0995819293,vm_smg_spray_t9_ads_elo_down
98428c84303b052,vm_smg_spray_t9_ads_elo_up
a002329f58d6099,vm_smg_spray_t9_ads_holo_down
f0fe676db7e472c,vm_smg_spray_t9_ads_holo_up
fa89947e7055553,vm_smg_spray_t9_ads_reddot_down
d0ad224e177b812,vm_smg_spray_t9_ads_reddot_up
619fa4daedebff,vm_smg_spray_t9_ads_reflex_down
a68ff7fd9c693b6,vm_smg_spray_t9_ads_reflex_up
551aff4c16ea2a3,vm_smg_spray_t9_crawl_b
551b3f4c16ea96f,vm_smg_spray_t9_crawl_f
551bdf4c16eba6d,vm_smg_spray_t9_crawl_l
5519ff4c16e8773,vm_smg_spray_t9_crawl_r
88ec7e4af179c80,vm_smg_spray_t9_crawl_in
455f5958f99d405,vm_smg_spray_t9_crawl_out
9685f3dcaade56f,vm_smg_spray_t9_fire
9c80157f0c70b02,vm_smg_spray_t9_fire_ads
eb5b1c88b99bda0,vm_smg_spray_t9_fire_last
c5e60679bb0b1f8,vm_smg_spray_t9_first_raise
b0fca05f9b679d3,vm_smg_spray_t9_gunbutt_swipe
5f7be6793690259,vm_smg_spray_t9_idle
98631931fa69bad,vm_smg_spray_t9_inspect
486bdb3a1570b90,vm_smg_spray_t9_pullout
da3d80c3f2e1604,vm_smg_spray_t9_pullout_quick
40e2f0b554179aa,vm_smg_spray_t9_putaway
8e0c0a2a9c4fad2,vm_smg_spray_t9_putaway_quick
b154f74b6820daa,vm_smg_spray_t9_reload
a3a28677223ae1b,vm_smg_spray_t9_reload_ads
51aefd0829e180c,vm_smg_spray_t9_reload_empty
1207286d316e1c5,vm_smg_spray_t9_reload_empty_ads
92b576fb4026906,vm_smg_spray_t9_sprint_loop
8b0964cda407817,vm_smg_spray_t9_sprint_in
aa3b796facd3c3c,vm_smg_spray_t9_sprint_out
3eb9df54bb73c69,vm_smg_spray_t9_sprint_pullout
c116e794258cec7,vm_smg_spray_t9_sprint_putaway

Sledgehammer
eb1e3152894203d,vm_sledgehammer_t9_ads_down
8dbb518a788c528,vm_sledgehammer_t9_ads_up
630fe2209221290,vm_sledgehammer_t9_crawl_b
63102220922195c,vm_sledgehammer_t9_crawl_f
6310c2209222a5a,vm_sledgehammer_t9_crawl_l
630ee220921f760,vm_sledgehammer_t9_crawl_r
777b3d585052edd,vm_sledgehammer_t9_crawl_in
7b780d1124e6746,vm_sledgehammer_t9_crawl_out
80669904779016f,vm_sledgehammer_t9_first_raise
22d6cc606cbe910,vm_sledgehammer_t9_idle
b1eb640ff9e687a,vm_sledgehammer_t9_inspect
5d3c6e03d6eef7e,vm_sledgehammer_t9_melee
f9eb225112ae3ef,vm_sledgehammer_t9_pullout
e24016f620e1f1d,vm_sledgehammer_t9_putaway
fe9c5dab93690d8,vm_sledgehammer_t9_sprint_in
cf7b3d9ebd89309,vm_sledgehammer_t9_sprint_loop
31e36a8c261381d,vm_sledgehammer_t9_sprint_out
ea1cbc1a8afa838,vm_sledgehammer_t9_sprint_pullout
2d18d24b5beb792,vm_sledgehammer_t9_sprint_putaway

Wakizashi
8fc614acf796b7d,vm_wakizashi_t9_crawl_b
8fc5d4acf7964b1,vm_wakizashi_t9_crawl_f
8fc534acf7953b3,vm_wakizashi_t9_crawl_l
8fc714acf7986ad,vm_wakizashi_t9_crawl_r
e1f431e8b319b46,vm_wakizashi_t9_crawl_in
edbfae67b0464a7,vm_wakizashi_t9_crawl_out
f8d8b42e8a9912e,vm_wakizashi_t9_first_raise
889c0a717afac53,vm_wakizashi_t9_idle
6c60937663c1377,vm_wakizashi_t9_inspect
5a71dcb248ef9bb,vm_wakizashi_t9_melee
de871c0953a4d62,vm_wakizashi_t9_pullout
dee22d0c4b63c7c,vm_wakizashi_t9_putaway
2fffad413f3fac1,vm_wakizashi_t9_sprint_in
7d6c066c0b8b444,vm_wakizashi_t9_sprint_loop
9fef75dcb01c9a2,vm_wakizashi_t9_sprint_out
7ad8277672f2c87,vm_wakizashi_t9_sprint_pullout
fd340de8c402af5,vm_wakizashi_t9_sprint_putaway

**Comment by Scobalula** [comment]
Thanks!
