### ISSUE TITLE
CW Ballistic Knife Animations (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#49]
Ballistic Knife
539b0196460082f,vm_ballistic_knife_t9_additive_empty
25863c00bbf0d96,vm_ballistic_knife_t9_ads_down
33730fb454e05e3,vm_ballistic_knife_t9_ads_up
9c828eb2aa326e1,vm_ballistic_knife_t9_crawl_b
9c82ceb2aa32dad,vm_ballistic_knife_t9_crawl_f
9c822eb2aa31caf,vm_ballistic_knife_t9_crawl_l
9c818eb2aa30bb1,vm_ballistic_knife_t9_crawl_r
21f3499731b9bba,vm_ballistic_knife_t9_crawl_in
90012beb3fcb7d3,vm_ballistic_knife_t9_crawl_out
d9629b56c9127ac,vm_ballistic_knife_t9_fall
8e6eeb545d67fbd,vm_ballistic_knife_t9_fire
4c8c923f3c4a2a9,vm_ballistic_knife_t9_fire_delay
8600f62cc89ae5a,vm_ballistic_knife_t9_first_raise
1d879c82061e462,vm_ballistic_knife_t9_first_raise_quick
16bbeb7426a635b,vm_ballistic_knife_t9_inspect
b890f4fed2fbb41,vm_ballistic_knife_t9_jump
66688df632c3723,vm_ballistic_knife_t9_jump_land
602997c816e7d3f,vm_ballistic_knife_t9_melee
bfe147a341f13a4,vm_ballistic_knife_t9_melee_finisher
3cb253eb6a47e66,vm_ballistic_knife_t9_melee_02
e8d5fddb591bcae,vm_ballistic_knife_t9_pullout
cfa0bce55bc5410,vm_ballistic_knife_t9_pullout_empty
9a54bd40f958c66,vm_ballistic_knife_t9_pullout_quick
25568abcf056560,vm_ballistic_knife_t9_putaway
b12d187af21f426,vm_ballistic_knife_t9_putaway_empty
62442f733320676,vm_ballistic_knife_t9_reload_empty
2adaee66430dc1d,vm_ballistic_knife_t9_sprint_in
47a7d37bc1c0a30,vm_ballistic_knife_t9_sprint_loop
cb8de7c46a37b86,vm_ballistic_knife_t9_sprint_out
4c2571227e7fa83,vm_ballistic_knife_t9_sprint_pullout
1d894816c243939,vm_ballistic_knife_t9_sprint_putaway

**Comment by EthanC** [comment]
Thanks
