### ISSUE TITLE
CW xModels Continued (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#56]
18d9bc0cface8bf,face

Song
9ee4dcb17e2b438,c_t9_gen_pl_starter4_song_tiger_arms
210ec93cce08f44,c_t9_gen_pl_starter4_song_tiger_arms_viewbody
9da079434662801,c_t9_gen_pl_starter4_song_tiger_head
8a9889dfe4a8866,c_t9_gen_pl_starter4_song_tiger_torso
cf769d5b84720e2,c_t9_gen_pl_starter4_song_tiger_torso_viewbody
e259c1594de9944,c_t9_gen_pl_starter4_song_tiger_lowerbody
5c138ef5402db58,c_t9_gen_pl_starter4_song_tiger_lowerbody_viewbody
5ecb9f92bb39939,c_t9_gen_pl_starter4_song_tiger_viewarms
4dd2e8d006ad8cb,c_t9_gen_pl_starter4_song_tiger_viewlegs

**Comment by EthanC** [comment]
Song's hashes were duplicates, but thanks.
