### ISSUE TITLE
Some CW xAnims (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#57]
74dee71efcd566e,gear
a8f12cc5f9a0c03,head
173c900e37ae1df,void
fda17c16237a47d,faces
d6392cec6bb13aa,event1
d6393cec6bb155d,event0
1bcb0cc19dd6a1b,vm_tr_fastburst_t9_ads_acog_down
96ea704780e8b7a,vm_tr_fastburst_t9_ads_acog_up
4deeb97ca185c6a,vm_tr_fastburst_t9_ads_base_down
5b7fee46f60ff0f,vm_tr_fastburst_t9_ads_base_up
7d4608dd9d1a17d,vm_tr_fastburst_t9_ads_holo_down
a0edbfa42d86268,vm_tr_fastburst_t9_ads_holo_up
de3be3635366ef7,vm_tr_fastburst_t9_ads_reddot_down
8ccdb0721c7a92e,vm_tr_fastburst_t9_ads_reddot_up
26f5c259257a60b,vm_tr_fastburst_t9_ads_reflex_down
a8b9297111c98ca,vm_tr_fastburst_t9_ads_reflex_up
367543f8fe3ab71,vm_tr_fastburst_t9_ads_scope4x_down
ccfbd13390a3464,vm_tr_fastburst_t9_ads_scope4x_up
d7334037d6808ef,vm_tr_fastburst_t9_crawl_b
d7330037d680223,vm_tr_fastburst_t9_crawl_f
2e900ee17e156bc,vm_tr_fastburst_t9_crawl_in
d733a037d681321,vm_tr_fastburst_t9_crawl_l
7f5c92777c9a49,vm_tr_fastburst_t9_crawl_out
d7324037d67edbf,vm_tr_fastburst_t9_crawl_r
1fcf07bb6cb2dae,vm_tr_fastburst_t9_fall
d09ad7b8fd6ab5b,vm_tr_fastburst_t9_fire
47321a244c9210e,vm_tr_fastburst_t9_fire_ads
6d1e97edfeba2ec,vm_tr_fastburst_t9_first_raise
ddddcda5170a63f,vm_tr_fastburst_t9_gunbutt_swipe
8e6e46407b0fa1d,vm_tr_fastburst_t9_idle
73270ab3b939649,vm_tr_fastburst_t9_inspect
9a01658c11f455b,vm_tr_fastburst_t9_jump
a7a01da3f0d4f39,vm_tr_fastburst_t9_jump_land
152b01e9d4bf5a4,vm_tr_fastburst_t9_pullout
b3588c0c756f568,vm_tr_fastburst_t9_pullout_quick
a4b71ae0bb5e3d6,vm_tr_fastburst_t9_putaway
1dd0d2eaecca3be,vm_tr_fastburst_t9_putaway_quick
8514b53b6a172c6,vm_tr_fastburst_t9_reload
eb09133bc5707f8,vm_tr_fastburst_t9_reload_empty
a1e656b902532f4,vm_tr_fastburst_t9_reload_empty_ext
59c135700b9c3bc,vm_tr_fastburst_t9_reload_empty_quick
856be3b57a4b696,vm_tr_fastburst_t9_reload_ext
e859a5bc5e1ad0e,vm_tr_fastburst_t9_reload_quick
8dc392984e1104b,vm_tr_fastburst_t9_sprint_in
68f65123b47f44a,vm_tr_fastburst_t9_sprint_loop
b9088cc2faa7b8,vm_tr_fastburst_t9_sprint_out
ed43922e51ebdad,vm_tr_fastburst_t9_sprint_pullout
63c506471b5be83,vm_tr_fastburst_t9_sprint_putaway
2e2782763e623fa,vm_tr_fastburst_t9_swim_uw_pullout
a7c9926b0ea6a54,vm_tr_fastburst_t9_swim_uw_putaway

**Comment by EthanC** [comment]
Thanks
