### ISSUE TITLE
CW xMaterials (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#58]
d743aeb3fed620f,mc/mtl_c_t8_mp_spe_seraph_body2_heist_duffel_bag_buckles_plastic
845bed0f477976,mc/mtl_c_t8_gen_eye_hazel
5a4368c7446f657,mc/mtl_c_t9_clown_mask_female
5dafb1718d3539,mc/mtl_c_t9_rus_pl_kgb_funnybone_head1_haircard1
5dacb1718d3020,mc/mtl_c_t9_rus_pl_kgb_funnybone_head1_haircard2
5db2b1718d3a52,mc/mtl_c_t9_rus_pl_kgb_funnybone_head1_haircard4
790bfa72a90ed5e,mc/mtl_c_t9_base_female_neck_white
a27c0150624190c,mc/mtl_c_t8_mp_spe_seraph_body2_heist_duffel_bag_cash
b1c7c8b15afcbf2,mc/mtl_c_t9_rus_knife_01_a
45a151b92ba8583,mc/mtl_c_t9_pins_clown_funnybone
73534dd1d500263,mc/mtl_c_t9_female_blouse_01
a45e85b243e97be,mc/mtl_c_t9_female_blouse_01_b_black
cc60bf4ff6d1185,mc/mtl_c_t9_belt_16
3c5e826717a0d25,mc/mtl_c_t9_female_suit_jacket_02_l_sleeve_purple
d6ccb4001fd8a22,mc/mtl_c_t9_clown_mask
a1f14126eba05d,mc/mtl_c_t8_mp_spe_seraph_body2_zipper
b5edebc8f8fc946,mc/mtl_c_t9_pins_clown
f3718f4afb3e8a8,mc/mtl_c_t8_mp_spe_seraph_body2_heist_duffel_bag_buckles_metal
a3d623a3b75ca68,mc/mtl_wpn_t9_tr_longburst_body_base_infest
b58a815a11cc70a,mc/mtl_wpn_t9_tr_longburst_sight_misc_base_infest
283f2570e60bbd2,mc/mtl_wpn_t9_tr_longburst_stock_mag_base_infest
1716ddb24370d4c,mc/mtl_c_t9_balaclava_02
1716edb24370eff,mc/mtl_c_t9_balaclava_03
dc07d1e7360add3,mc/mtl_c_t9_balaclava_03_green
68e8f5ae7b9920a,mc/mtl_c_t9_balaclava_02_grey
7a504e1e6d9fe3a,mc/mtl_c_t9_usa_helmet_combat_kevlar_code
14ad17cc8d624bb,mc/mtl_c_t9_cub_cap_03
18b9a1550f6cae1,mc/mtl_c_t9_cub_cap_03_decal
4326e401a7eac03,mc/mtl_c_t9_base_male_neck_black
4a05fa14634603d,mc/mtl_c_t9_base_male_neck_white
5303ec1c19d5304,mc/mtl_c_t9_uk_pl_mi6_glam_head1_face
685a8d92fe269f4,mc/mtl_c_t9_uk_pl_mi6_dystopia_head1_face
beb24ef8f4ffdee,mc/mtl_c_t9_uk_pl_mi6_heist_head1_face
eb0ea03a66e5596,mc/mtl_c_t9_uk_pl_mi6_glam_head1_haircard1
8989c5704c06d48,mc/mtl_c_t9_uk_pl_mi6_coal_head1_haircard1
9812a1fde0bc946,mc/mtl_c_t9_uk_pl_mi6_dystopia_head1_haircard1
8989f5704c07261,mc/mtl_c_t9_uk_pl_mi6_coal_head1_haircard2
8989e5704c070ae,mc/mtl_c_t9_uk_pl_mi6_coal_head1_haircard3
981291fde0bc793,mc/mtl_c_t9_uk_pl_mi6_dystopia_head1_haircard2
3707e915dbcac83,mc/mtl_c_t9_usa_pl_navyseal_breaker_head1_haircard1
3707f915dbcae36,mc/mtl_c_t9_usa_pl_navyseal_breaker_head1_haircard2
37080915dbcafe9,mc/mtl_c_t9_usa_pl_navyseal_breaker_head1_haircard3
d7d6b5fb384aeed,mc/mtl_c_t9_usa_pl_navyseal_gigawatt_head1_haircard1
d7d685fb384a9d4,mc/mtl_c_t9_usa_pl_navyseal_gigawatt_head1_haircard2
77773ddfdc128,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_blue
27730e271204f77,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_black
9b0315bccc065ea,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_gold
a2e5762b9323d93,mc/mtl_c_t9_usa_pl_adler_red_head1_haircard1
a2e5862b9323f46,mc/mtl_c_t9_usa_pl_adler_red_head1_haircard2
2134832a40e03bd,mc/mtl_c_t9_usa_pl_adler_hostage_head1_face
8fdff5409cf7d6d,mc/mtl_c_t9_usa_pl_adler_wire_head1_haircard1
8fdfc5409cf7854,mc/mtl_c_t9_usa_pl_adler_wire_head1_haircard2
4b970daafea533a,mc/mtl_c_t9_usa_pl_cia_sogman_head1_face
c48e14f3c067312,mc/mtl_c_t9_usa_pl_cia_covert_head1_face
feda030bdf8c4a7,mc/mtl_c_t9_usa_pl_cia_commando_head1_face
29497c19c3a2489,mc/mtl_c_t9_balaclava_03_klown
fe18bfed317daac,mc/mtl_c_t9_balaclava_04_skull
1716cdb24370b99,mc/mtl_c_t9_balaclava_05
dfd8c84cb21a26e,mc/mtl_c_t9_balaclava_05_brown
17169db24370680,mc/mtl_c_t9_balaclava_06
103f56e44c69032,mc/mtl_c_t9_balaclava_06_gray
fb6a25ecb89bea4,mc/mtl_c_t9_balaclava_06_green
a268b5afc2413d,mc/mtl_c_t9_balaclava_06_maroon
c8b6ccd00f96ef7,mc/mtl_c_t9_balaclava_06_purple
bee09a0a7c49019,mc/mtl_c_t9_cub_pl_dgi_slasher_head1_face
2fba3dbfd5f7dd4,mc/mtl_c_t9_cub_pl_dgi_brawler_head1_haircard1
2fba6dbfd5f82ed,mc/mtl_c_t9_cub_pl_dgi_brawler_head1_haircard2
edf770140bfabba,mc/mtl_c_t9_cub_pl_dgi_brawler_head1_hairshell1
2ae75d3c4edf5a1,mc/mtl_c_t9_cub_pl_dgi_infiltration_head1_hair_eyelashes
7b229f9eedc9aa4,mc/mtl_c_t9_sunglasses_01
7b22bf9eedc9e0a,mc/mtl_c_t9_sunglasses_03
7b222f9eedc8ebf,mc/mtl_c_t9_sunglasses_08
7af23f9eeda5a9b,mc/mtl_c_t9_sunglasses_13
7af28f9eeda631a,mc/mtl_c_t9_sunglasses_14
8bf4a4213bbde6e,mc/mtl_c_t9_cub_pl_dgi_infiltration_head1_face
305802df7021d1f,mc/mtl_c_t9_cub_pl_dgi_infiltration_head1_hair_eyebrowshell
f857f9ac36bbe50,mc/mtl_c_t9_cub_pl_dgi_infiltration_head1_hair_beardshell
fbc7b104511ba75,mc/mtl_c_t9_headband_01
fd7afcea87cbe47,mc/mtl_c_t9_cub_pl_dgi_infiltration_head1_hair_beardcard1
2c10b82b69af747,mc/mtl_c_t9_firefighter_helmet_01
8d0c0bd4118d073,mc/mtl_c_t9_firefighter_helmet_01_visor
9beebbceb488824,mc/mtl_c_t9_rus_hose_01
69f0a530c93b3dc,mc/mtl_c_t9_rus_spetsnaz_gas_mask_01
77a3ace96cab557,mc/mtl_c_t9_rus_spetsnaz_gas_mask_01_glass
37047190baafb90,mc/mtl_c_t9_rus_spetsnaz_gasmask_filter
79e3c9b7103502a,mc/mtl_c_t9_rus_pl_spetsnaz_head1_face
d5ddb7404e836c2,mc/mtl_c_t9_rus_pl_spetsnaz_infiltration_fur
eb2d92456955ee9,mc/mtl_c_t9_rus_pl_spetsnaz_infiltration_fur1
eb2d624569559d0,mc/mtl_c_t9_rus_pl_spetsnaz_infiltration_fur2
eb2d72456955b83,mc/mtl_c_t9_rus_pl_spetsnaz_infiltration_fur3
eb2dc2456956402,mc/mtl_c_t9_rus_pl_spetsnaz_infiltration_fur4
95939819a41e7f3,mc/mtl_c_t9_ballistic_mask_toxin
d39496c9ea405b,mc/mtl_c_t9_usa_pl_bulldozer_hawk_mask
371998b3aa3e9a1,mc/mtl_c_t9_usa_pl_bulldozer_boom_faceshield
48e778f6329988,mc/mtl_c_t9_usa_pl_bulldozer_boom_plastic_tape
260e3ba120cd6e3,mc/mtl_c_t9_usa_pl_bulldozer_boom_license_plate
b2bb5b61153e1b2,mc/mtl_c_t9_usa_pl_bulldozer_boom_chestplate
b612188a7105acb,mc/mtl_c_t9_usa_pl_bulldozer_boom_faceshield_mount
cdd090af6796d5a,mc/mtl_c_t9_usa_pl_bulldozer_01_sleeves
4f06f4b07f243e0,mc/mtl_c_t9_usa_pl_bulldozer_hawk_mask_harness
9a2b62ca6a3b6b,mc/mtl_c_t9_welders_mask_bulldozer
619898d4c70183f,mc/mtl_c_t9_usa_pl_bulldozer_01_leg_straps
986ccd5dc6296c6,mc/mtl_c_t9_nic_pl_smuggler_head1_face
33221d5a8053c22,mc/mtl_c_t9_nic_pl_smuggler_head1_hair_braid
cd1a38c551ab307,mc/mtl_c_t9_nic_pl_smuggler_head1_hair_eyebrowshell
b0fb769527899d8,mc/mtl_c_t9_nic_pl_smuggler_head1_hair_haircard2
933d949a90f6012,mc/mtl_c_t9_nic_pl_smuggler_thigh_strap
97c56b72d00d613,mc/mtl_c_t9_nic_pl_smuggler_body_chest
93bb61d40ff17d0,mc/mtl_c_t9_nic_pl_smuggler_headband
67ea4c0ded154ab,mc/mtl_c_t9_nic_pl_smuggler_sheath1
3eee80c3f62ca12,mc/mtl_c_t9_nic_pl_smuggler_armband
c9bf22fa86939dd,mc/mtl_c_t9_nic_pl_smuggler_bandage
3fa1cd58ec80536,mc/mtl_c_t9_nic_pl_smuggler_bandage_bright
622631e03032f76,mc/mtl_c_t9_nic_pl_smuggler_bandage_dirty
160aedefb26944d,mc/mtl_c_t9_nic_pl_smuggler_body_arms
c8998120ee47e2d,mc/mtl_c_t9_nic_pl_smuggler_hand_strap
1648b7ffbad5865,mc/mtl_c_t9_nic_pl_smuggler_necklace
1b32239e541adb,mc/mtl_c_t9_nic_pl_smuggler_necklace_silver
268a63fd2987b3,mc/mtl_c_t9_gen_pl_starter3_stone_stoned_head1_hairshell
e9e480b41350287,mc/mtl_c_t9_dummy_head
2fb62d24a678308,mc/mtl_c_t9_rus_compressor_01
d919ef95da6bbdd,mc/mtl_c_t9_knife_01
d919bf95da6b6c4,mc/mtl_c_t9_knife_02
d9503f95da99d53,mc/mtl_c_t9_knife_10
d9505f95da9a0b9,mc/mtl_c_t9_knife_12
603f728fc8b5109,mc/mtl_c_t9_rus_spetsnaz_chernobyl_harness_01_metal
7907bdf66cb6602,mc/mtl_c_t9_rus_straps_01
213340b1b6ad269,mc/mtl_c_t9_pistol_magazine_02
bda50a810e175c6,mc/mtl_c_t9_uk_double_mag_pouch_01
c0eb78db94b40dc,mc/mtl_c_t9_knife_scabbard_10
8415c99587b6cd4,mc/mtl_c_t9_knife_02_scabbard_blood
1133c98ae6711,mc/mtl_c_t9_knife_02_scabbard_muddy
a7953a65f868e1b,mc/mtl_c_t9_knife_02_scabbard
d0df0293f9042c0,mc/mtl_c_t9_gloves_01
d0df3293f9047d9,mc/mtl_c_t9_gloves_02
d0df2293f904626,mc/mtl_c_t9_gloves_03
d0df4293f90498c,mc/mtl_c_t9_gloves_05
d0df7293f904ea5,mc/mtl_c_t9_gloves_06
d679d774a839637,mc/mtl_c_t9_usa_knife_04_bandage
f4c03c503d8924d,mc/mtl_c_t9_usa_pl_adler_infiltration_holster
2c6e3a5f7d503a0,mc/mtl_c_t9_rus_spetsnaz_chernobyl_harness_02
6ed88ce0ac71c40,mc/mtl_c_t9_shoulder_padding_01
96f31a60042aef7,mc/mtl_c_t9_rus_bag_01
93ad59509bbed11,mc/mtl_c_t9_rus_mini_tank_01
cb2dc4b432ea952,mc/mtl_c_t9_rus_spetsnaz_patch
f16584f432871bf,mc/mtl_c_t9_usa_knife_04_bandage_red
e52540a649c8259,mc/mtl_c_t9_hazmat_suit_03_sleeves
c9d0c3f60bc626a,mc/mtl_c_t9_navy_seal_altimeter_01
462803b646b919d,mc/mtl_c_t9_navy_seal_altimeter_01_glass
d953e5719e6b685,mc/mtl_c_t9_navy_seal_altimeter_01_dial
db05f1475415fa9,mc/mtl_c_t9_beanie_knit_green
94908b4d902fdf5,mc/mtl_c_t9_beanie_knit_red
df27ed10d6b9ae6,mc/mtl_c_t9_beanie_knit_blue
a7e4f5402253c47,mc/mtl_c_t9_bandana_01_green
a0d4017163fd6f2,mc/mtl_c_t9_bandana_02_red
268db5a1ca8cbf2,mc/mtl_c_t9_bandana_02_green
83c47469e086174,mc/mtl_c_t9_base_male_foot_mideast
4cd0e84a4f6f49b,mc/mtl_c_t9_rus_sso_smersh_loadout_harness_01
3c68c4ecd4917f3,mc/mtl_c_t9_fra_dgse_gun_holster_02_red
4ec3dfbd08ac83d,mc/mtl_c_t9_fra_dgse_gun_holster_01_brown
ad5ea3cab28aefe,mc/mtl_c_t9_cassette_player_01
77fe2a3442cab87,mc/mtl_c_t9_cassette_player_01_blue
56e872cea6e8b63,mc/mtl_c_t9_cassette_player_01_pink
41f23c50fc73084,mc/mtl_c_t9_decal_button_outside_01_black
8014342b6d5a85c,mc/mtl_c_t9_decal_button_outside_01_green
6bbe8c297db3fa7,mc/mtl_c_t9_headphones_01
c0491aa8dd27e4,mc/mtl_c_t9_headphones_01_pink
d466c9adc81166f,mc/mtl_c_t9_shirt_02
9d41eedb22d2fcc,mc/mtl_c_t9_shirt_02_blue
92bac226bd2328,mc/mtl_c_t9_shirt_02_yellow
59470cf247793bc,mc/mtl_c_t9_knife_camo_wrap_04
656323a5001bf97,mc/mtl_c_t9_shotgun_shell_01
a9b4022321b7139,mc/mtl_c_t9_cassette_player_01_glass
b506bac48085b9b,mc/mtl_c_t9_base_male_torso_mideast
e334390f2b3a448,mc/mtl_c_t9_usa_claymore_bag_02
bc8822aa12745b1,mc/mtl_c_t9_shotgun_shell_shoulder_strap_01
3e5e48423312b94,mc/mtl_c_t9_bracelet_07
3e5e2842331282e,mc/mtl_c_t9_bracelet_01
3e5e68423312efa,mc/mtl_c_t9_bracelet_05
3e5db8423311c49,mc/mtl_c_t9_bracelet_08
3e5da8423311a96,mc/mtl_c_t9_bracelet_09
d1b6c7d42fc339b,mc/mtl_c_t9_arm_wrap_01
d1b6e7d42fc3701,mc/mtl_c_t9_arm_wrap_03
d1b6f7d42fc38b4,mc/mtl_c_t9_arm_wrap_04
f34021de686ff6e,mc/mtl_c_t9_base_male_arm_mideast_dirt
6f35eae011b82ab,mc/mtl_c_t9_ger_gsg9_assault_helmet_01
195918feadf7d22,mc/mtl_c_t9_ger_pl_west_gsg9_klown_head1_face
1bb1684fedc50f0,mc/mtl_c_t9_fra_dgse_leg_pouches_01_black_dirt
2cd7369322577ee,mc/mtl_c_t9_axe_01
9c6996eca678de6,mc/mtl_c_t9_rus_grenade_02_black
75bbf3808d5d5f3,mc/mtl_c_t9_cub_holster_02_klown
23490ee0d54a94e,mc/mtl_c_t9_ger_assault_pack_02_black_blood
88147f88cce83b2,mc/mtl_c_t9_decal_duct_tape_02
5821350f6550028,mc/mtl_c_t9_decal_duct_tape_02_klown
a34fb9ef3749e3a,mc/mtl_c_t9_ger_knife_01
a0603cdab8092a6,mc/mtl_c_t9_ger_g3_dual_mag_pouch_01_black_dirt
ed634106c51945d,mc/mtl_c_t9_grenade_bandolier
bc11c350a3e55f6,mc/mtl_c_t9_grenade_bandolier_dirty
e2f7b6df4a3206e,mc/mtl_c_t9_kneepad_01_damaged
1ba239be7949d4b,mc/mtl_c_t9_navy_seal_harness_01
406c544ed309d41,mc/mtl_c_t9_m18_claymore_bag_01_beige_dirt
422a79978f9971f,mc/mtl_c_t9_ger_bgs_eagle_pocket_shoulder_patch_01
63537b68c4c12d,mc/mtl_c_t9_usa_pl_deltaforce_infiltration_gloves_c
dc011f0920edd4a,mc/mtl_c_t9_usa_pl_woods_whirlwind_tattoo_arms
6c30ce22c243d17,mc/mtl_c_t9_cub_cap_03_green
ccf8703bfe02d0b,mc/mtl_c_t9_cub_cap_03_red
25033dab50da620,mc/mtl_c_t9_cub_cap_03_blue
b3ba3c6429b845a,mc/mtl_c_t9_rope_05
b3b9ec6429b7bdb,mc/mtl_c_t9_rope_02
b3ba4c6429b860d,mc/mtl_c_t9_rope_04
357caf6db694191,mc/mtl_c_t9_usa_small_pouch_07
966b9824d06a9ef,mc/mtl_c_t9_usa_bullet_magazine_01
5250eb14a170477,mc/mtl_c_t9_kneepad_02
5250db14a1702c4,mc/mtl_c_t9_kneepad_03
9f707d570aa0690,mc/mtl_c_t9_shirt_03_a_dirt
d31f055f3b9c283,mc/mtl_c_t9_shirt_02_a
d31f155f3b9c436,mc/mtl_c_t9_shirt_02_b
d31f255f3b9c5e9,mc/mtl_c_t9_shirt_02_c
33dd98ee5658486,mc/mtl_c_t9_comms_device_01
78e7596a6e5cbf0,mc/mtl_c_t9_chain_swagger_01
bd8f9492a0c093e,mc/mtl_c_t9_charge_canister_01
93bf8380f156592,mc/mtl_c_t9_usa_sog_jacket_01_a_left_sleeves
1822515df00fbbf,mc/mtl_c_t9_usa_sog_jacket_01_a_right_sleeves
c4a25978c339ba3,mc/mtl_c_t9_knife_12_sheath
43a992e4ffcdfe2,mc/mtl_c_t9_usa_sog_tactical_vest_01
681bc607d60406a,mc/mtl_c_t9_usa_sog_tactical_vest_01_pouch
ce8cd1254e6434d,mc/mtl_c_t9_shirt_02_hostage
bd16a79f45a447b,mc/mtl_c_t9_paperboy_cap_01
3e3f8ab0f52afbb,mc/mtl_c_t9_turtle_neck_sweater_01_a_rightsleeve
cbec82685897606,mc/mtl_c_t9_turtle_neck_sweater_01_a_leftsleeve
13134f4f7ce2c15,mc/mtl_c_t9_longsleeve_shirt_12
90a2cd50aa71515,mc/mtl_c_t9_longsleeve_shirt_12_a_torso
c1bb0f8d5af70f4,mc/mtl_c_t9_longsleeve_shirt_12_a_rightsleeve
1e66016aedb40bb,mc/mtl_c_t9_longsleeve_shirt_12_a_leftsleeve
5a839ec61e6f82b,mc/mtl_c_t9_tactical_leg_strap_01
2cb773fe71a2da5,mc/mtl_c_t9_jeans_03
2cb703fe71a21c0,mc/mtl_c_t9_jeans_04
5b1ca7f5498d3ca,mc/mtl_c_t9_40mm_grenade_shell
215362e45655ffc,mc/mtl_c_t9_bullet_proof_vest_leather_01
215392e45656515,mc/mtl_c_t9_bullet_proof_vest_leather_02
f08a06b85f327d6,mc/mtl_c_t9_usa_smoke_grenade_01_red
47f2274162978d9,mc/mtl_c_t9_electro_pads_cable
391626bc4880097,mc/mtl_c_t9_usa_pl_adler_hostage_arms_dirt
a5d1ca794ad6aaa,mc/mtl_c_t9_arm_bandage_wrap_04_bright
94eb8fe3e2bbdce,mc/mtl_c_t9_usa_sog_bracelet_01
a46c1df7372b1d5,mc/mtl_c_t9_usa_sog_bracelet_01_brown
9c9fc19b5c32417,mc/mtl_c_t9_arm_bandage_wrap_02
9c9fb19b5c32264,mc/mtl_c_t9_arm_bandage_wrap_03
b3e8382c1087e0f,mc/mtl_c_t9_electro_pads
1d33e5e2f9b7c78,mc/mtl_c_t8_bo_hero_menendez_head1_hair_haircard4
1d33f5e2f9b7e2b,mc/mtl_c_t8_bo_hero_menendez_head1_hair_haircard5
1d3435e2f9b84f7,mc/mtl_c_t8_bo_hero_menendez_head1_hair_haircard1
1d3445e2f9b86aa,mc/mtl_c_t8_bo_hero_menendez_head1_hair_haircard2
1d3455e2f9b885d,mc/mtl_c_t8_bo_hero_menendez_head1_hair_haircard3
9c45b85cfea2887,mc/mtl_c_t9_arm_bandage_wrap_04_hostage
cc282fb34c96d26,mc/mtl_c_t9_usa_pl_adler_red_head1_beardshell
eb3f8d543357ffd,mc/mtl_c_t9_usa_pl_adler_hostage_torso
4ede913f2f69bca,mc/mtl_c_t9_usa_pl_adler_infiltration_jeans_brown
d0850c73c6885ec,mc/mtl_c_t9_usa_pl_adler_infiltration_boots_brown
fe67a9e42e9f2fb,mc/mtl_c_t9_knife_02_blood
4f7298738cd8303,mc/mtl_c_t9_shirt_02_decal_hostage
4caf94131ebe234,mc/mtl_c_t9_usa_holster_01_brown
91bad4c5753d018,mc/mtl_c_t9_usa_seige_glove_right_tan
f93b94c76e30a5c,mc/mtl_c_t9_usa_seige_glove_right_red
95fad1797adb093,mc/mtl_c_t9_usa_seige_glove_left_tan
d8e3f7cbff838d4,mc/mtl_c_t9_usa_seige_glove_left_blue
72571178d190e2f,mc/mtl_c_t9_usa_seige_glove_left_red
606492195a0fcbe,mc/mtl_c_t9_zmb_hellhound_crawler_pustules_small
d3d5d62120c89ce,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_blue02
f0ce24dde6247de,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_orange
bb7435a7fb869f7,mc/mtl_c_t9_usa_pl_adler_infiltration_flight_jacket_tan
54e54bc8ed63e4e,mc/mtl_c_t9_usa_pl_adler_infiltration_jeans_brown_dirt
58f2af29c9f47af,mc/mtl_c_t9_usa_pl_adler_infiltration_rope_yellow
8f91244cf0b2b0a,mc/mtl_c_t9_usa_pl_adler_infiltration_rope_red
393676fd76f23bf,mc/mtl_c_t9_usa_pl_adler_infiltration_rope_blue
a98a38c55cd5b70,mc/mtl_c_t9_usa_pl_adler_infiltration_rope_gray
6f636da1a16b2ca,mc/mtl_c_t9_usa_pl_adler_infiltration_tape
285ac0b5b90b106,mc/mtl_c_t9_usa_pl_adler_infiltration_tape_red
cb28b2f7f801b26,mc/mtl_c_t9_usa_pl_adler_infiltration_tape_green
ee4ac5a9313571,mc/mtl_c_t9_usa_pl_adler_infiltration_radio

**Comment by EthanC** [comment]
Thanks
