### ISSUE TITLE
Cold War XModels (Hash Verified)

### ISSUE THREAD

**Issue by EpicZombieSlayer115** [Scobalula/GreyhoundPackageIndex#59]
de2c15ff30ab920,attach_t9_bp_optic_reflex_gknight_ads
699a6d260022ccc,attach_t9_charm_crystal_eleph
de813714cd25cfd,attach_t9_charm_crystal_elephant
f532a36e0a0287f,attach_t9_charm_family_crest
421e9bcc330abcc,attach_t9_charm_japanese_bell
d4dc869589de1d,attach_t9_charm_japanese_flute
41e8a94ef075f7f,attach_t9_charm_luckycat
f2e07dbb3a7c18c,attach_t9_charm_mil_hardhart
d258336a5c88462,attach_t9_charm_mil_hardhat
699ef094d3f6cc6,attach_t9_charm_olive_crown
3e9c109bff19ae3,attach_t9_charm_tac_snowman
c93d3560bc2027e,attach_t9_charm_tacsnowman
5d4e3008598eb99,attach_t9_minimal_stock_01_lmg_accurate_zweed_view
66ced4f9a0b7cc,attach_t9_minimal_stock_01_lmg_accurate_zweed_world
6da1418960d87ed,attach_t9_tac_mag_01_loot_ar_slowhandling_view
a6bbe770171a310,attach_t9_tac_mag_01_loot_ar_slowhandling_world
e129a6086546d03,attach_t9_tac_mag_01_loot_smg_accurate_view
f4972c0c5ce4c56,attach_t9_tac_mag_01_loot_smg_accurate_world
d68ad0cec577abd,attach_t9_tac_mag_01_pro_loot_ar_slowhandling_view
3d8dbe471518b00,attach_t9_tac_mag_01_pro_loot_ar_slowhandling_world
e1795c0c83f5a53,attach_t9_tac_mag_01_pro_loot_smg_accurate_view
15409682ccb0186,attach_t9_tac_mag_01_pro_loot_smg_accurate_world
7194ed19557fcba,c_t8_zmb_mob_hero_dempsey_lowerbody1_viewbody1_cst
187a5d4d315bdf8,c_t8_zmb_mob_hero_nikolai_lowerbody1_viewbody1_cst
fd4565398a78c01,c_t8_zmb_mob_hero_richtofen_lowerbody1_viewbody1_cst
e762481ecc45c81,c_t8_zmb_mob_hero_takeo_lowerbody1_viewbody1_cst
45bea83ca77756b,c_t8_zmb_mob_hero_zombie_blood_lowerbody1_viewbody1
c488537a846bdf9,c_t8_zmb_mob_hero_zombie_blood_torso1_viewbody1
b09f04d7fc9607c,c_t9_cub_pl_dgi_tropas_arms_ms
aa7d84d7f766d59,c_t9_cub_pl_dgi_tropas_arms_pc
ab1ee4d7f7ee740,c_t9_cub_pl_dgi_tropas_arms_sy
1521ac202942b42,c_t9_cub_pl_dgi_tropas_arms_viewbody_ms
1931ac202cbc237,c_t9_cub_pl_dgi_tropas_arms_viewbody_pc
18f1cc202c7dcc6,c_t9_cub_pl_dgi_tropas_arms_viewbody_sy
d7eec6c5bda74ca,c_t9_cub_pl_dgi_tropas_lowerbody_ms
d89ec6c5be47c4f,c_t9_cub_pl_dgi_tropas_lowerbody_pc
d85de6c5be07bae,c_t9_cub_pl_dgi_tropas_lowerbody_sy
d2ea94a620f1b48,c_t9_cub_pl_dgi_tropas_lowerbody_viewbody_ms
d54c14a6230134d,c_t9_cub_pl_dgi_tropas_lowerbody_viewbody_pc
d5ea74a62383ba4,c_t9_cub_pl_dgi_tropas_lowerbody_viewbody_sy
803412222b2dc54,c_t9_cub_pl_dgi_tropas_torso_ms
7d74922228daf01,c_t9_cub_pl_dgi_tropas_torso_pc
7e12f222295d758,c_t9_cub_pl_dgi_tropas_torso_sy
57f074e4fdcb2ca,c_t9_cub_pl_dgi_tropas_torso_viewbody_ms
58a074e4fe6ba4f,c_t9_cub_pl_dgi_tropas_torso_viewbody_pc
585f94e4fe2b9ae,c_t9_cub_pl_dgi_tropas_torso_viewbody_sy
eaa27b85ae58ac7,c_t9_cub_pl_dgi_tropas_viewarms_ms
e6a07b85aaf7072,c_t9_cub_pl_dgi_tropas_viewarms_pc
e601db85aa7414f,c_t9_cub_pl_dgi_tropas_viewarms_sy
92cfa02b4850a8d,c_t9_cub_pl_dgi_tropas_viewlegs_ms
9740202b4c11ac8,c_t9_cub_pl_dgi_tropas_viewlegs_pc
977f402b4c4ebd5,c_t9_cub_pl_dgi_tropas_viewlegs_sy
132941cd49b2726,c_t9_gen_pl_starter1_hunter_inferno_lowerbody
71ee1359f8737dc,c_t9_ger_pl_west_bomber_arms_viewbody
57f471e20cea335,c_t9_usa_pl_adler_bloodhound_arms
f538d54666316fc,c_t9_usa_pl_adler_bloodhound_head
b766126c37c41b7,c_t9_usa_pl_adler_bloodhound_lowerbody
e83187c5ee9dc89,c_t9_usa_pl_adler_bloodhound_lowerbody_viewbody
a567d8bf8f8ed21,c_t9_usa_pl_adler_bloodhound_torso
84013ba47ff853b,c_t9_usa_pl_adler_bloodhound_torso_viewbody
4641f8fd9098f58,c_t9_usa_pl_adler_bloodhound_viewarms
ca4a72cb36d312,c_t9_usa_pl_adler_bloodhound_viewlegs
f0dd46099e5f392,c_t9_usa_pl_adler_traveler_arms
3cdb6a8bdb73423,c_t9_usa_pl_adler_traveler_head
6357151d27019e,c_t9_usa_pl_adler_traveler_lowerbody
5f2bfbe20d4076a,c_t9_usa_pl_adler_traveler_lowerbody_viewbody
cc820ec76d133c4,c_t9_usa_pl_adler_traveler_torso
6ca5fc42a7b52d8,c_t9_usa_pl_adler_traveler_torso_viewbody
48e9e1960fce853,c_t9_usa_pl_adler_traveler_viewarms
5d25eeffae0b505,c_t9_usa_pl_adler_traveler_viewlegs
eca1a3379e3d94c,c_t9_usa_pl_cia_penumbra_arms_viewbody
7f9bd4fa8896ba8,c_t9_usa_pl_cia_penumbra_arms_viewbody_pc
71ef81759399199,c_t9_usa_pl_cia_penumbra_head
9906c59587ccc7f,c_t9_usa_pl_cia_penumbra_head_pc
e2e45311343955c,c_t9_usa_pl_cia_penumbra_lowerbody
5c747346e98d798,c_t9_usa_pl_cia_penumbra_lowerbody_pc
486e839eb32efe0,c_t9_usa_pl_cia_penumbra_lowerbody_viewbody
c3a9ec1f781604c,c_t9_usa_pl_cia_penumbra_lowerbody_viewbody_pc
64f6e79871053de,c_t9_usa_pl_cia_penumbra_torso
ceebc38c856c30e,c_t9_usa_pl_cia_penumbra_torso_pc
8e0fa8cd3ed81aa,c_t9_usa_pl_cia_penumbra_torso_viewbody
f39bfaf4e7c56ea,c_t9_usa_pl_cia_penumbra_torso_viewbody_pc
810caf8de595b61,c_t9_usa_pl_cia_penumbra_viewarms
c611e77a9ea6a7,c_t9_usa_pl_cia_penumbra_viewarms_pc
f94601177ceb0f3,c_t9_usa_pl_cia_penumbra_viewlegs
547fdce3560470d,c_t9_usa_pl_cia_penumbra_viewlegs_pc
4773c27a37fb8c9,c_t9_usa_pl_woods_mellow_arms
cf975ef87d8efb3,c_t9_usa_pl_woods_mellow_arms_viewbody
f77a1d9e7f82bd8,c_t9_usa_pl_woods_mellow_head
fd2b3ab86fe021b,c_t9_usa_pl_woods_mellow_lowerbody
f6962cb98ddb965,c_t9_usa_pl_woods_mellow_lowerbody_viewbody
9f008b18443354d,c_t9_usa_pl_woods_mellow_torso
416577df9eb829f,c_t9_usa_pl_woods_mellow_torso_viewbody
65f98a7ebdb0934,c_t9_usa_pl_woods_mellow_viewarms
8997b4dda0a3c3e,c_t9_usa_pl_woods_mellow_viewlegs
bc9d9bd89fe6688,c_t9_usa_pl_woods_slaughter_arms
b8de4b601fbff74,c_t9_usa_pl_woods_slaughter_arms_viewbody
91c93825cf3f611,c_t9_usa_pl_woods_slaughter_head
3ee742f7b1a8094,c_t9_usa_pl_woods_slaughter_lowerbody
e3afd71d4cf87c8,c_t9_usa_pl_woods_slaughter_lowerbody_viewbody
1212bf5d9b7f5b6,c_t9_usa_pl_woods_slaughter_torso
b079c2a9ed40712,c_t9_usa_pl_woods_slaughter_torso_viewbody
ca413c0325fad09,c_t9_usa_pl_woods_slaughter_viewarms
19da854a4cff8fb,c_t9_usa_pl_woods_slaughter_viewlegs
27b7003748ab3c2,collision_clip_256x256x10
3e5983bba3575b4,collision_missile_256x256x10
335412e20287362,defaultvehicle
b75bf7dc6f1fd8e,defaultweapon
f2359791696c97c,face
8984407b541af93,fx
ef5c1d2a91b28e4,fx_axis_createfx
6cb500c3ecf634a,fx_bullet_chain
d27d08fefaf944d,fx_debris_stone_01
174b284f642e826,fx_pistol_shell
9c6e3772db36e76,fx_pistol_shell_blur
2a84e676627f3,fx_rifle_shell
f7f48477b8bde9d,fx_rifle_shell_blur
2e7c3748845facf,p7_crate_ammo_metal_green
b3d395688eea732,p7_debris_rockychunks_small_02
3728c018639984a,p7_fe_paintshop_bkgd_01
be416df5036a5a1,p7_fxp_debris_dirt_clod_01_brown
167d97b4d0142ad,p7_fxp_debris_wood_splinter_01
167d67b4d013d94,p7_fxp_debris_wood_splinter_02
167d77b4d013f47,p7_fxp_debris_wood_splinter_03
dec297328e5a7a5,p7_pipe_metal_hp_4_straight_64_grey_dk
41adf8f37966054,p8_cos_floor_gantry_center_decal
67908ea96b92301,p8_lv8_picture_hostel_01
6790bea96b9281a,p8_lv8_picture_hostel_04
aa86463c633353e,p8_mad_tape_gaffer_8
8e3c30c62d5fca8,p8_zm_red_coin_gold
7c8a446a8b067ea,p8_zm_zod_glass_cracked
95ecb7cb66b6d9a,p9_apo_gold_bar_01
939c72ec7c5412c,p9_bonuscard_gearhound
eb13b83cf350a91,p9_bonuscard_primary_gunfighter
5d890d8f2d7be57,p9_core_cabinet_wall_tape_corner_01
5d891d8f2d7c00a,p9_core_cabinet_wall_tape_corner_02
25dd8a9ad227bdc,p9_core_cabinet_wall_tape_lethal
206f4e717c021e4,p9_core_cabinet_wall_tape_primary
6aecd6d45cf3c0b,p9_core_cabinet_wall_tape_straight_02
e0b51c6d885462f,p9_core_cabinet_wall_tape_tactical
248b82a13216742,p9_core_frontend_blood_decal_zm_01
499f54cbfc202c2,p9_core_frontend_cigarette_pack_03
40b142b4f38f9d2,p9_core_frontend_grenade_frag_world
a1e9b70d7a722a1,p9_core_frontend_plane_structure_divider_02_frame
156172a91687457,p9_core_frontend_weapon_inspect_icon
cd6a165332a8f2d,p9_core_storage_metal_01_label_01
55282ff32d39a8b,p9_fe2_terrain_foliage_plant_fern_02
24089905526dbb9,p9_fe2_terrain_zm_lobby_01
b7164528441e7f5,p9_fxanim_mp_planemortar_01_mod
f93e1bf903e219b,p9_fxanim_zm_gold_essence_trap_mod
3d316352b229f35,p9_fxanim_zm_gold_gas_delivery_device_set_mod
4be063bcb4464d7,p9_fxp_debris_mud_2
4be053bcb446324,p9_fxp_debris_mud_3
e0865c4e2e8b99f,p9_fxp_zm_fld_frost_blast_shard
cf55b52993b7807,p9_heart_name_be_mine
29d33df7174b193,p9_heart_name_dream_on
a47080d4ccbd2c1,p9_heart_name_my_hero
8ebd6e90da65663,p9_heart_name_no_thanks
92271a3312c931c,p9_heart_name_noob
183edbd9cca1d67,p9_heart_name_owned
cce928fc15d2233,p9_heart_name_true_love
8f8cece6f20ce30,p9_rus_magazine_flat_faster
876b17e38c93178,p9_sfh_red_circus_scotch_tape
29eadf43833cfec,p9_zm_wand_canister_aethershroud
f2117b2befc5af0,p9_zm_wand_canister_frostblast
758c70bfe7bbbe8,wpn_t8_default_weapon_view
abc095a7bb87763,wpn_t8_default_weapon_world
592a1a0efe2d6f,wpn_t8_shock_charge_view
e87069c5e84cbe9,wpn_t9_ar_damage_animedark_view
ee3e8f2ac186bc,wpn_t9_ar_damage_animedark_world
7fa3f1312c1099b,wpn_t9_ar_fastfire_legion_view_sy
4054b8ad6038676,wpn_t9_ar_fastfire_legion_world_sy
c4265f57dac91cf,wpn_t9_ar_mercenary_codemam_mag_view_ms
ca465f57dff5c2a,wpn_t9_ar_mercenary_codemam_mag_view_pc
c9a6bf57df711d7,wpn_t9_ar_mercenary_codemam_mag_view_sy
7bbec4603b62d46,wpn_t9_ar_mercenary_codemam_mag_world_ms
7e1dc4603d6e153,wpn_t9_ar_mercenary_codemam_mag_world_pc
7ddfe4603d33242,wpn_t9_ar_mercenary_codemam_mag_world_sy
773245f9837e5fb,wpn_t9_ar_mercenary_codemam_view_ms
784145f98463dfe,wpn_t9_ar_mercenary_codemam_view_pc
77a1a5f983df3ab,wpn_t9_ar_mercenary_codemam_view_sy
8e5885d22b6fda2,wpn_t9_ar_mercenary_codemam_world_ms
925885d22ece197,wpn_t9_ar_mercenary_codemam_world_pc
9228a5d22eaaf26,wpn_t9_ar_mercenary_codemam_world_sy
2e9405d4948db1b,wpn_t9_ar_mercenary_knight_view
4da3956d209966e,wpn_t9_ar_mercenary_knight_world
553900f8844e830,wpn_t9_ar_mobility_dfoilage_view
e5e2bba51155ecb,wpn_t9_ar_mobility_dfoilage_world
6de39dc337cfed7,wpn_t9_knife_ballistic_spycraft_view
3c69628b4452aaa,wpn_t9_knife_ballistic_spycraft_world
a7435bbb8ca59cc,wpn_t9_knife_bowie_predator_view_sy
df6ba3c760bc23b,wpn_t9_knife_bowie_predator_world_sy
ed0a5bea948ec01,wpn_t9_melee_machete_daether_view
78dbdd4d3328434,wpn_t9_melee_machete_daether_world
783e57b72eaf0ee,wpn_t9_smg_heavy_cdummy_view
c59f2b2a5ec7831,wpn_t9_smg_heavy_cdummy_world
b67f74c6149cc37,wpn_t9_sniper_powersemi_cb_animelight_view
6a11bc68746918a,wpn_t9_sniper_powersemi_cb_animelight_world
bdd33ce10c641e7,wpn_t9_tr_damagesemi_cdummy_view
2777e3c55d408da,wpn_t9_tr_damagesemi_cdummy_world
c7e691c4ce76d0,wpn_t9_tr_precisionsemi_speckled_view
a0582b5de32efeb,wpn_t9_tr_precisionsemi_speckled_world
1bb92358aa2d0d7,wpn_t9_zm_wand_cannister_frost_blast_view
edffb89cfe9c952,wrist_watch_t9_s1_analog_broken_fancy
f8739e552d7ab25,wrist_watch_t9_s1_analog_broken_fancy_world
d4687b3f5ebcc45,wrist_watch_t9_s1_analog_retroren_02_view
9560ec5ba5320a8,wrist_watch_t9_s1_analog_retroren_02_world
65a482fdd13ff23,wrist_watch_t9_s2_analog_black_silver_view
b53b267630fbcf6,wrist_watch_t9_s2_analog_black_silver_world
6707e048cacbc34,wrist_watch_t9_s2_analog_dark_aether_view
65087dc1872ebaf,wrist_watch_t9_s2_analog_dark_aether_world
9749f565dcd0d34,wrist_watch_t9_s2_digital_mayan_view
6a625e2725c8eaf,wrist_watch_t9_s2_digital_mayan_world
629b3c02acb42d8,wrist_watch_t9_s2_digital_mini_map_view
88251957f193873,wrist_watch_t9_s2_digital_mini_map_world
c92dc3d9a594c33,wrist_watch_t9_s2_digital_river_slasher_view
6bdef812edfbae6,wrist_watch_t9_s2_digital_river_slasher_world
82282ed7d49f85a,wrist_watch_t9_s3_digital_ultrafunk_world

**Comment by EthanC** [comment]
Thanks
