### ISSUE TITLE
CW Weapon xAnims Continued (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#60]
546d39151436bf,vm_ar_accurate_t9_active_idle
67005b614fc368f,vm_ar_accurate_t9_reload_empty_fastmag
f1be0aa810a2162,vm_ar_accurate_t9_reload_empty_fastmag_ads
601014c8f4c7012,vm_ar_accurate_t9_reload_empty_mixclip
654d88dc87d0153,vm_ar_accurate_t9_reload_empty_mixclip_ads
d9096074259afd,vm_ar_accurate_t9_reload_fastmag
e138fb83de64820,vm_ar_accurate_t9_reload_fastmag_ads
14ad8c23b84d6b0,vm_ar_accurate_t9_reload_mixclip
d0107e7dff7e219,vm_ar_accurate_t9_reload_mixclip_ads
945a029425b13ec,vm_tr_longburst_t9_active_idle
5cb19b9e15b7b96,vm_tr_longburst_t9_reload_empty_fastmag
78c9d97cd76c027,vm_tr_longburst_t9_reload_empty_fastmag_ads
7c842430847806f,vm_tr_longburst_t9_reload_empty_mixclip
a87a36bb99bd602,vm_tr_longburst_t9_reload_empty_mixclip_ads
6e91a4d5cfb9364,vm_tr_longburst_t9_reload_fastmag
4ee277d14e32b8d,vm_tr_longburst_t9_reload_fastmag_ads
d3ff3d1cc442dfd,vm_tr_longburst_t9_reload_mixclip
f53b2580a2b8b20,vm_tr_longburst_t9_reload_mixclip_ads
76054bfdaf92320,vm_ar_damage_t9_reload_empty_fastmag
1f9c055f9af2fa,vm_ar_damage_t9_reload_fastmag
3b856a0b5cb85d3,vm_ar_damage_t9_reload_mixclip
84bf0ca0a75169d,vm_ar_slowhandling_t9_active_idle
1d48ecbedc37099,vm_ar_slowhandling_t9_reload_empty_fastmag
652d3a43d192acc,vm_ar_slowhandling_t9_reload_empty_fastmag_ads
65a875286405c,vm_ar_slowhandling_t9_reload_empty_mixclip
e9f8aa668b8d195,vm_ar_slowhandling_t9_reload_empty_mixclip_ads
abb170eaf75257b,vm_ar_slowhandling_t9_reload_fastmag
d069306d294aeee,vm_ar_slowhandling_t9_reload_fastmag_ads
f8e2dbf75b6787e,vm_ar_slowhandling_t9_reload_mixclip
36b80f73cf4d5f,vm_ar_slowhandling_t9_reload_mixclip_ads
2025d7835e53497,vm_ar_fastfire_t9_active_idle
8fa10924496baa7,vm_ar_fastfire_t9_reload_empty_fastmag
c621ef9bd9d5caa,vm_ar_fastfire_t9_reload_empty_fastmag_ads
e236998115924ca,vm_ar_fastfire_t9_reload_empty_mixclip
7a2b246846c2d7b,vm_ar_fastfire_t9_reload_empty_mixclip_ads
281fefd2c461465,vm_ar_fastfire_t9_reload_fastmag
2093909137fb138,vm_ar_fastfire_t9_reload_fastmag_ads
db8a8eab2f87238,vm_ar_fastfire_t9_reload_mixclip
e227375ed06c2d1,vm_ar_fastfire_t9_reload_mixclip_ads
ca99e2e32f72759,vm_ar_standard_t9_reload_empty_mixclip
5150ddf31b91b9a,vm_ar_standard_t9_reload_fastmag
3d9c4bea086488b,vm_ar_standard_t9_reload_fastmag_ads
8acc87a87e7fb73,vm_ar_standard_t9_reload_mixclip
34a48ceeff21e3,vm_tr_precisionsemi_t9_reload_mixclip
a123750624f025c,vm_tr_damagesemi_t9_reload_empty_mixclip
fe95742fa554a7e,vm_tr_damagesemi_t9_reload_mixclip
906485a8fc3851c,vm_tr_fastburst_t9_active_idle
626e852445c2a06,vm_tr_fastburst_t9_reload_empty_fastmag
715d8e3a8b0b317,vm_tr_fastburst_t9_reload_empty_fastmag_ads
c2605521842561f,vm_tr_fastburst_t9_reload_empty_mixclip
eea52053932dc72,vm_tr_fastburst_t9_reload_empty_mixclip_ads
876c77cbfbfaa94,vm_tr_fastburst_t9_reload_fastmag
7433ade0f84643d,vm_tr_fastburst_t9_reload_fastmag_ads
e63c84ca1a96dad,vm_tr_fastburst_t9_reload_mixclip
a594b3ae4ec010,vm_tr_fastburst_t9_reload_mixclip_ads
17d5ee953cda11b,vm_tr_powerburst_t9_active_idle
270d8078695b943,vm_tr_powerburst_t9_reload_empty_fastmag
f773929c50a7f86,vm_tr_powerburst_t9_reload_empty_fastmag_ads
907816ee325e4e6,vm_tr_powerburst_t9_reload_empty_mixclip
2770e145bddbdb7,vm_tr_powerburst_t9_reload_empty_mixclip_ads
f1f9f958d35d921,vm_tr_powerburst_t9_reload_fastmag
9e8be90bf577604,vm_tr_powerburst_t9_reload_fastmag_ads
f2f0cf0a7b47ba4,vm_tr_powerburst_t9_reload_mixclip
dbe5d5557bdc3cd,vm_tr_powerburst_t9_reload_mixclip_ads
31b8a5c307c958a,vm_smg_handling_t9_active_idle
bb43cd7590de9f9,vm_smg_handling_t9_reload_empty_mixclip
ccaccf0a6b39dec,vm_smg_handling_t9_reload_empty_mixclip_ads
a395126dd927853,vm_smg_handling_t9_reload_mixclip
a4599c01f620b16,vm_smg_handling_t9_reload_mixclip_ads
207a6c51491c3cc,vm_smg_standard_t9_reload_empty_fastmag
ea0deaab75c6196,vm_smg_standard_t9_reload_fastmag
496b48695a3c0b9,vm_smg_heavy_t9_reload_empty_mixclip
d59e3029f56eeac,vm_smg_heavy_t9_reload_empty_mixclip_ads
2e39cdf4ef18a60,vm_lmg_light_t9_active_idle
5a70d36f5bfb2fb,vm_lmg_light_t9_reload_empty_mixclip
854fd11e5e534d9,vm_lmg_light_t9_reload_mixclip
1955e646cb4f5e3,vm_lmg_accurate_t9_reload_mixclip
9655d94055ebf9,vm_sniper_cannon_t9_reload_empty_mixclip
be77f71f1f4bfec,vm_sniper_cannon_t9_reload_empty_mixclip_ads
70caab5bfaa8a53,vm_sniper_cannon_t9_reload_mixclip
f21b6bf963c3d16,vm_sniper_cannon_t9_reload_mixclip_ads
f335abc34d7a096,vm_sniper_powersemi_t9_active_idle
d7972dbb7eecfed,vm_sniper_powersemi_t9_reload_empty_mixclip
8953d4b89973650,vm_sniper_powersemi_t9_reload_empty_mixclip_ads
71072e675e1f507,vm_sniper_powersemi_t9_reload_mixclip
d7f20feb3db64a,vm_sniper_powersemi_t9_reload_mixclip_ads
ef48cd6c476462e,vm_sniper_standard_t9_active_idle
5975df369d750e5,vm_sniper_standard_t9_reload_empty_mixclip
aba451d21b0f5b8,vm_sniper_standard_t9_reload_empty_mixclip_ads
bea4d93d7c4cb2f,vm_sniper_standard_t9_reload_mixclip
16cac6e1a4b1c2,vm_sniper_standard_t9_reload_mixclip_ads
eaaf7ce7c97177d,vm_pistol_revolver_t9_reload_mixclip
8e42d90241bcca0,vm_pistol_revolver_t9_reload_mixclip_ads
eb99c242eb94368,vm_smoke_grenade_t9_throw
15db5e1c95124e5,vm_frag_grenade_t9_throw
38b5d507c58dd41,vm_hatchet_t9_throw
c443558296aa3e9,vm_semtex_grenade_t9_throw
2bc96a368ed963d,vm_concussion_grenade_t9_throw
272a35cfaf76098,vm_shotgun_fullauto_t9_active_idle
c53066a5b18283e,vm_shotgun_fullauto_t9_ads_base_down
90f795966bfbc0b,vm_shotgun_fullauto_t9_ads_base_up
4ac794abf2383b7,vm_shotgun_fullauto_t9_ads_reflex_down
2ac69978d26b1ee,vm_shotgun_fullauto_t9_ads_reflex_up
136e46a240bc07b,vm_shotgun_fullauto_t9_crawl_b
136e86a240bc747,vm_shotgun_fullauto_t9_crawl_f
bef335b3fe48168,vm_shotgun_fullauto_t9_crawl_in
136e26a240bbd15,vm_shotgun_fullauto_t9_crawl_l
a74b80d98b0cb8d,vm_shotgun_fullauto_t9_crawl_out
136d46a240ba54b,vm_shotgun_fullauto_t9_crawl_r
14dd7916a4d5e72,vm_shotgun_fullauto_t9_fall
63344919135eac7,vm_shotgun_fullauto_t9_fire
a01e2cee199b80a,vm_shotgun_fullauto_t9_fire_ads
9d2c2a98de98fa0,vm_shotgun_fullauto_t9_first_raise
a2635b9811d00bb,vm_shotgun_fullauto_t9_gunbutt_swipe
2a91336e1e7a5a1,vm_shotgun_fullauto_t9_idle
16918d23ff05a85,vm_shotgun_fullauto_t9_inspect
19bd2beba3e2c7,vm_shotgun_fullauto_t9_jump
137a389a31e120d,vm_shotgun_fullauto_t9_jump_land
19fa52b2ab5e838,vm_shotgun_fullauto_t9_pullout
8f2116979004fc,vm_shotgun_fullauto_t9_pullout_quick
5cf668e37c4f792,vm_shotgun_fullauto_t9_putaway
ba92451719afbea,vm_shotgun_fullauto_t9_putaway_quick
4b4c844a7fc055c,vm_shotgun_fullauto_t9_reload_in
e48dad2c5ba313d,vm_shotgun_fullauto_t9_reload_loop
87274a954d49a69,vm_shotgun_fullauto_t9_reload_out
b62a9ef9c9e79df,vm_shotgun_fullauto_t9_sprint_in
c4d4395981bc4be,vm_shotgun_fullauto_t9_sprint_loop
a0d5d273dd58304,vm_shotgun_fullauto_t9_sprint_out
84a005a14831211,vm_shotgun_fullauto_t9_sprint_pullout
1581fdd68a289cf,vm_shotgun_fullauto_t9_sprint_putaway
1e32ec241f040de,vm_shotgun_fullauto_t9_swim_uw_pullout
c61702a87647570,vm_shotgun_fullauto_t9_swim_uw_putaway

**Comment by EthanC** [comment]
Thanks
