### ISSUE TITLE
CW Season Three Reloaded Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#62]
d2a8a4d949eedd1,c_t9_usa_pl_rambo_arms
2d1eaa73c4a914b,c_t9_usa_pl_rambo_arms_viewbody
e771089896d88a0,c_t9_usa_pl_rambo_head
af863586d40e663,c_t9_usa_pl_rambo_lowerbody
289b711555775dd,c_t9_usa_pl_rambo_lowerbody_viewbody
54662fd32b7fb75,c_t9_usa_pl_rambo_torso
eef71be863db0f7,c_t9_usa_pl_rambo_torso_viewbody
bf03d898fadd2ec,c_t9_usa_pl_rambo_viewarms
26640b3a6522776,c_t9_usa_pl_rambo_viewlegs
1939bf85a44fb9d,c_t9_usa_pl_mcclane_arms
71eaba38878ff8f,c_t9_usa_pl_mcclane_arms_viewbody
423c1affaf249a4,c_t9_usa_pl_mcclane_head
1e3385ad966e37f,c_t9_usa_pl_mcclane_lowerbody
ecbb43eb75f5601,c_t9_usa_pl_mcclane_lowerbody_viewbody
50ba49b80f07929,c_t9_usa_pl_mcclane_torso
d0df921b9306e53,c_t9_usa_pl_mcclane_torso_viewbody
44411ec69cfbdf0,c_t9_usa_pl_mcclane_viewarms
817d586e3f6aea,c_t9_usa_pl_mcclane_viewlegs

**Comment by EthanC** [comment]
Good work

**Comment by ItsNatoriousB** [comment]
I have more
