### ISSUE TITLE
CW Season Three Reloaded Continued (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#64]
3b2bf09db2608ce,c_t9_ger_pl_maxis_bride_arms
c08f0ce987e9ec7,c_t9_ger_pl_maxis_bride_head
82b2b3a920ce6fa,c_t9_ger_pl_maxis_bride_arms_viewbody
b65028ec6522f88,c_t9_ger_pl_maxis_bride_torso
836bbd0e959ea74,c_t9_ger_pl_maxis_bride_torso_viewbody
3d80e4ba65f296a,c_t9_ger_pl_maxis_bride_lowerbody
4fecccd92fe943e,c_t9_ger_pl_maxis_bride_lowerbody_viewbody
755d8622f2e33f7,c_t9_ger_pl_maxis_bride_viewarms
924117eb441fa99,c_t9_ger_pl_maxis_bride_viewlegs

**Comment by EthanC** [comment]
Thanks
