### ISSUE TITLE
CW Season Three Reloaded Weapon Anims (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#65]
f51c6bda672e98,vm_sniper_quickscope_t9_inspect_manguish
554b61b2a341fd5,vm_baseball_bat_t9_ads_down
be54a0a81871900,vm_baseball_bat_t9_ads_up
6fbd35b1b00368,vm_baseball_bat_t9_crawl_b
6fc135b1b00a34,vm_baseball_bat_t9_crawl_f
dd08a3cee06b365,vm_baseball_bat_t9_crawl_in
6fbb35b1b00002,vm_baseball_bat_t9_crawl_l
2675a888011dcce,vm_baseball_bat_t9_crawl_out
6fad35b1afe838,vm_baseball_bat_t9_crawl_r
dcd77247d413477,vm_baseball_bat_t9_first_raise
91d2375acbd34b2,vm_baseball_bat_t9_inspect
d7b5df5a4d0c3bf,vm_baseball_bat_t9_melee_miss
24cd72d43b73d7,vm_baseball_bat_t9_pullout
cc18cc91edf85a5,vm_baseball_bat_t9_putaway
ef97f58cc83a660,vm_baseball_bat_t9_sprint_in
17c6ac287ce0621,vm_baseball_bat_t9_sprint_loop
7b4cfe38e2d5565,vm_baseball_bat_t9_sprint_out
f8157f098d00ae0,vm_baseball_bat_t9_sprint_pullout
b1a8857e8d3d6da,vm_baseball_bat_t9_sprint_putaway
c553a5c55ab096d,vm_pistol_fullauto_t9_ads_base_down
bd2ef15d04ee638,vm_pistol_fullauto_t9_ads_base_up
f28e9b0067d8884,vm_pistol_fullauto_t9_ads_reflex_down
806cf7e9fab1d05,vm_pistol_fullauto_t9_ads_reflex_up
384d257f25b37e0,vm_pistol_fullauto_t9_crawl_b
384d657f25b3eac,vm_pistol_fullauto_t9_crawl_f
60f1b70d1206f4d,vm_pistol_fullauto_t9_crawl_in
384e057f25b4faa,vm_pistol_fullauto_t9_crawl_l
a6a1db3615d2116,vm_pistol_fullauto_t9_crawl_out
384e257f25b5310,vm_pistol_fullauto_t9_crawl_r
cb8ea726b369daa,vm_pistol_fullauto_t9_fire
556d49136293e1b,vm_pistol_fullauto_t9_fire_ads
e0f6b36a09f331f,vm_pistol_fullauto_t9_first_raise
1d96a5bc2d8af2c,vm_pistol_fullauto_t9_gunbutt_swipe
cd6cbef3975e460,vm_pistol_fullauto_t9_idle
63e3757f3683b26,vm_pistol_fullauto_t9_idle_empty
4247ec8459c69ca,vm_pistol_fullauto_t9_inspect
daf9a96d576b19f,vm_pistol_fullauto_t9_pullout
d68e8ed180e8aad,vm_pistol_fullauto_t9_putaway
b877bc24f11070b,vm_pistol_fullauto_t9_reload
1c07a55a51d1a0d,vm_pistol_fullauto_t9_reload_empty
b176331388625d5,vm_pistol_fullauto_t9_reload_empty_ext
bdc6398bcb557a6,vm_pistol_fullauto_t9_reload_empty_mixclip
256b8fabd8dec77,vm_pistol_fullauto_t9_reload_empty_mixclip_ads
5347fbc94c97e77,vm_pistol_fullauto_t9_reload_ext
536d64ed5c11e64,vm_pistol_fullauto_t9_reload_mixclip
d776e9b55dae68d,vm_pistol_fullauto_t9_reload_mixclip_ads
9e45f9baac32768,vm_pistol_fullauto_t9_sprint_in
6c64d097145cc39,vm_pistol_fullauto_t9_sprint_loop
b4e9833104dd8d,vm_pistol_fullauto_t9_sprint_out
25234fcbe2a0a8,vm_pistol_fullauto_t9_sprint_pullout
fdee3c3b3604fa2,vm_pistol_fullauto_t9_sprint_putaway
9a7da5abb1b33fb,vm_pistol_fullauto_t9_swim_uw_putaway
84bf9fd0bf4ef67,vm_pistol_fullauto_t9_dw_ads_base_down
aea94547d62023e,vm_pistol_fullauto_t9_dw_ads_base_up
39b79f0552fa2be,vm_pistol_fullauto_t9_dw_crawl_b
39b7df0552fa98a,vm_pistol_fullauto_t9_dw_crawl_f
b40560bfd6fa47,vm_pistol_fullauto_t9_dw_crawl_in
39b73f0552f988c,vm_pistol_fullauto_t9_dw_crawl_l
e8e4666192efecc,vm_pistol_fullauto_t9_dw_crawl_out
39b89f0552fbdee,vm_pistol_fullauto_t9_dw_crawl_r
601efd37fecbadb,vm_pistol_fullauto_t9_dw_fire_l
601ddd37fec9c45,vm_pistol_fullauto_t9_dw_fire_r
c18effdc84f9e39,vm_pistol_fullauto_t9_dw_first_raise
efb5b29f9bbb666,vm_pistol_fullauto_t9_dw_gunbutt_swipe
dcce28f64f2705d,vm_pistol_fullauto_t9_dw_idle_l
43b7539badb48a8,vm_pistol_fullauto_t9_dw_inspect
208ca2f6b26d15d,vm_pistol_fullauto_t9_dw_pullout
c6b4331de9efc89,vm_pistol_fullauto_t9_dw_pullout_quick
ecbe8d8072dac13,vm_pistol_fullauto_t9_dw_putaway
e7e7b5e535c757b,vm_pistol_fullauto_t9_dw_putaway_quick
a574b6b7f70628c,vm_pistol_fullauto_t9_dw_reload_empty_l
a57616b7f7087ee,vm_pistol_fullauto_t9_dw_reload_empty_r
e4237ea379423aa,vm_pistol_fullauto_t9_dw_reload_l
e4239ea37942710,vm_pistol_fullauto_t9_dw_reload_r
bbd818add4043be,vm_pistol_fullauto_t9_dw_sprint_in
cf446d5e94035eb,vm_pistol_fullauto_t9_dw_sprint_loop
19e84f5ea1a37ff,vm_pistol_fullauto_t9_dw_sprint_out
53be937dbdab0af,vm_pistol_fullauto_t9_dw_swim_uw_pullout
300302711e5d8dd,vm_pistol_fullauto_t9_dw_swim_uw_putaway

**Comment by EthanC** [comment]
Thanks
