### ISSUE TITLE
CW UI Images Season Three (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#66]
be511e69f50052a,ui_icon_operators_uk_pl_sas_blackknight
ddf4c0a41c05d67,ui_icon_operators_usa_mcclane
22358048eecb853,ui_icon_operators_usa_rambo
b84f387f33253f7,ui_icon_mtx_tileimage_operator_rambo_v0
602f7011af891a2,ui_icon_mtx_tileimage_operator_fra_mademoiselle_v1
602f6011af88fef,ui_icon_mtx_tileimage_operator_fra_mademoiselle_v2
e991d7971983642,ui_icon_mtx_tileimage_operator_sas_blackknight_v0
60c70f66f472e35,ui_icon_mtx_tileimage_operator_cia_advisor_v1
60c6df66f47291c,ui_icon_mtx_tileimage_operator_cia_advisor_v2
60c6ef66f472acf,ui_icon_mtx_tileimage_operator_cia_advisor_v3
c70af881b67a318,ui_icon_mtx_tileimage_operator_jungle_warfare_v0
4aacb3d341f60b9,ui_icon_mtx_tileimage_operator_maxis_bride_v0
e03af0c6221fdfe,ui_icon_mtx_tileimage_operator_starter3_stone_stoned_v0
5547030fbb63c24,ui_icon_mtx_tileimage_operator_starter3_stone_squelch_v0
cb97cf0440dd3b9,ui_icon_mtx_tileimage_operator_starter2_finishline_v0
75df8bc52426288,ui_icon_mtx_tileimage_operator_starter1_hunter_frontline_v1
75dfbbc524267a1,ui_icon_mtx_tileimage_operator_starter1_hunter_frontline_v2
fc20df831fde3c,ui_icon_mtx_tileimage_operator_starter4_song_tiger_blue_v0
48e6b21b5261b57,ui_icon_mtx_tileimage_operator_starter4_song_tiger_tan_v0
8030db01afbb3c2,ui_icon_mtx_tileimage_operator_starter5_gun_v1

**Comment by EthanC** [comment]
Thanks
