### ISSUE TITLE
hi i opened b04 and tried to click the button "load game" but it says error 

### ISSUE THREAD

**Issue by zxelo** [Scobalula/GreyhoundPackageIndex#7]

**Comment by EthanC** [comment]
This isn't the correct repository for issues relating to [Greyhound](https://github.com/Scobalula/Greyhound), try the [Support Server](https://discord.gg/fGVpV39).

Regardless, the error you're running into is likely due to the current update not being supported at this time, as it clearly states.

**Comment by zxelo** [comment]
I can’t even load into the discord because the link has expired, also can u
try to help me
