### ISSUE TITLE
More Weapon xAnims (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#71]
27355cf740bdc29,vm_nailgun_t9_ads_base_down
cd55dc52d446e5c,vm_nailgun_t9_ads_base_up
9e8c63ab18ffb94,vm_nailgun_t9_crawl_b
9e8c23ab18ff4c8,vm_nailgun_t9_crawl_f
673d1bbb79aba01,vm_nailgun_t9_crawl_in
9e8bc3ab18fea96,vm_nailgun_t9_crawl_l
b2de2f8dc74c0e2,vm_nailgun_t9_crawl_out
9e8b63ab18fe064,vm_nailgun_t9_crawl_r
afc6e2b9bb1896e,vm_nailgun_t9_fire
f773e68cb23ce0f,vm_nailgun_t9_fire_ads
62edbc3a7f4985b,vm_nailgun_t9_first_raise
5986a2f01234f30,vm_nailgun_t9_gunbutt_swipe
9a043c70fc6622e,vm_nailgun_t9_inspect
2d3752c9d00f9b,vm_nailgun_t9_pullout
255f043da0d8d73,vm_nailgun_t9_pullout_quick
56e05bdcabc72d1,vm_nailgun_t9_putaway
87eeb56bb90f61d,vm_nailgun_t9_putaway_quick
1e49c172cfa3fef,vm_nailgun_t9_reload
525c62a6fea8541,vm_nailgun_t9_reload_empty
c561c022f2e354,vm_nailgun_t9_sprint_in
498f390b7ed7825,vm_nailgun_t9_sprint_loop
f4e597b4620bac1,vm_nailgun_t9_sprint_out
5e754f9f7ead8a4,vm_nailgun_t9_sprint_pullout
ee016896654c6d6,vm_nailgun_t9_sprint_putaway
c6d43280484e701,vm_nailgun_t9_swim_uw_pullout
14070509ba9859f,vm_nailgun_t9_swim_uw_putaway
1175d3844c2c075,vm_lmg_fastfire_t9_ads_acog_down
aca0284227bc7a0,vm_lmg_fastfire_t9_ads_acog_up
ed72d6533d55050,vm_lmg_fastfire_t9_ads_base_down
c4e51def6b99749,vm_lmg_fastfire_t9_ads_base_up
7d8969e31bf5d6b,vm_lmg_fastfire_t9_ads_holo_down
1d5ef9dc34e822a,vm_lmg_fastfire_t9_ads_holo_up
adcbc2831ae539d,vm_lmg_fastfire_t9_ads_reddot_down
3fd9fd53104ca88,vm_lmg_fastfire_t9_ads_reddot_up
ccec60539d5bdc1,vm_lmg_fastfire_t9_ads_reflex_down
fff5d7636399154,vm_lmg_fastfire_t9_ads_reflex_up
4d9222fe2a0b7,vm_lmg_fastfire_t9_ads_scope4x_down
700e00c6eb586ee,vm_lmg_fastfire_t9_ads_scope4x_up
845183b4600f481,vm_lmg_fastfire_t9_crawl_b
8451c3b4600fb4d,vm_lmg_fastfire_t9_crawl_f
e3739b7f37f95da,vm_lmg_fastfire_t9_crawl_in
845123b4600ea4f,vm_lmg_fastfire_t9_crawl_l
d30a592e0c17873,vm_lmg_fastfire_t9_crawl_out
845083b4600d951,vm_lmg_fastfire_t9_crawl_r
ec81dda944959d,vm_lmg_fastfire_t9_fire
984026e0d353400,vm_lmg_fastfire_t9_fire_ads
1b3ddcb5238e7fa,vm_lmg_fastfire_t9_first_raise
6e01054a789388d,vm_lmg_fastfire_t9_gunbutt_swipe
77f385fa1ebb9df,vm_lmg_fastfire_t9_idle
3e0ae02739e4dbb,vm_lmg_fastfire_t9_inspect
de34f2dd1a77b0e,vm_lmg_fastfire_t9_pullout
8b7e241e0a4406,vm_lmg_fastfire_t9_pullout_quick
1ab57fbeb1b23c0,vm_lmg_fastfire_t9_putaway
b505fa8e01e7394,vm_lmg_fastfire_t9_putaway_quick
fc030a750329e90,vm_lmg_fastfire_t9_reload
5de4de738389d96,vm_lmg_fastfire_t9_reload_empty
3535d448147e206,vm_lmg_fastfire_t9_reload_empty_ext
dda50f689cad12c,vm_lmg_fastfire_t9_reload_ext
5c4706faa659bbd,vm_lmg_fastfire_t9_sprint_in
62fc1de3f0216d0,vm_lmg_fastfire_t9_sprint_loop
4891abe9527d4a6,vm_lmg_fastfire_t9_sprint_out
9ba86fd12aaaa3,vm_lmg_fastfire_t9_sprint_pullout
305dd88dfaa5859,vm_lmg_fastfire_t9_sprint_putaway
4f12d27b352da0,vm_lmg_fastfire_t9_swim_uw_pullout
f4e4339ce1c229a,vm_lmg_fastfire_t9_swim_uw_putaway
2e296485c0134f5,vm_ar_slowfire_t9_ads_acog_down
80b4f8dcb5da820,vm_ar_slowfire_t9_ads_acog_up
a266754b13c4d0,vm_ar_slowfire_t9_ads_base_down
98f9ee89f9b77c9,vm_ar_slowfire_t9_ads_base_up
9a3cfae48fdd1eb,vm_ar_slowfire_t9_ads_holo_down
f173ca76c3062aa,vm_ar_slowfire_t9_ads_holo_up
a0d52d534fc7c1d,vm_ar_slowfire_t9_ads_reddot_down
5c8d8e548433f08,vm_ar_slowfire_t9_ads_reddot_up
bff5cb23d23e641,vm_ar_slowfire_t9_ads_reflex_down
1ca96864d7805d4,vm_ar_slowfire_t9_ads_reflex_up
dbd611ecdb17237,vm_ar_slowfire_t9_ads_scope4x_down
1c75663edd57c6e,vm_ar_slowfire_t9_ads_scope4x_up
86e50e907f70d01,vm_ar_slowfire_t9_crawl_b
86e54e907f713cd,vm_ar_slowfire_t9_crawl_f
a5b08f888ab375a,vm_ar_slowfire_t9_crawl_in
86e4ae907f702cf,vm_ar_slowfire_t9_crawl_l
9ab505059e4e4f3,vm_ar_slowfire_t9_crawl_out
86e40e907f6f1d1,vm_ar_slowfire_t9_crawl_r
8f3f8393c4cdf1d,vm_ar_slowfire_t9_fire
5a7d1aea260d580,vm_ar_slowfire_t9_fire_ads
ef52ad4fb1ac87a,vm_ar_slowfire_t9_first_raise
8ab4964bec7ad0d,vm_ar_slowfire_t9_gunbutt_swipe
f86aebb34f4035f,vm_ar_slowfire_t9_idle
409e6b03594663b,vm_ar_slowfire_t9_inspect
e0c87db939d938e,vm_ar_slowfire_t9_pullout
256b7343548b886,vm_ar_slowfire_t9_pullout_quick
1d490a9ad113c40,vm_ar_slowfire_t9_putaway
d1b98b8f75ce814,vm_ar_slowfire_t9_putaway_quick
d657ec2c8b2e410,vm_ar_slowfire_t9_reload
db4b55130091716,vm_ar_slowfire_t9_reload_empty
41189c0449a345e,vm_ar_slowfire_t9_reload_fastmag
eb9a1b5cb6c557f,vm_ar_slowfire_t9_reload_fastmag_ads
5e7c4071b5da1f7,vm_ar_slowfire_t9_reload_mixclip
662300e57671f3a,vm_ar_slowfire_t9_reload_mixclip_ads
2c4eac25c944a84,vm_ar_slowfire_t9_reload_quick
23f1b2d2389083d,vm_ar_slowfire_t9_sprint_in
3710ee7e7e3f750,vm_ar_slowfire_t9_sprint_loop
c65bab36c593226,vm_ar_slowfire_t9_sprint_out
dcc53e05eca4dd9,vm_ar_slowfire_t9_sprint_putaway
f7fa97f7e835620,vm_ar_slowfire_t9_swim_uw_pullout
e7ed9e6d16a4b1a,vm_ar_slowfire_t9_swim_uw_putaway
1fd8b6a2390b28,vm_smg_accurate_t9_ads_acog_down
24fcff3c2bfd0a1,vm_smg_accurate_t9_ads_acog_up
645c58877265e8d,vm_smg_accurate_t9_ads_base_down
faed11ffa680158,vm_smg_accurate_t9_ads_base_up
4d8521328a75f62,vm_smg_accurate_t9_ads_holo_down
22af88b02e66207,vm_smg_accurate_t9_ads_holo_up
4684044c2151328,vm_smg_accurate_t9_ads_reddot_down
94c3a037e8498a1,vm_smg_accurate_t9_ads_reddot_up
856e7f5542cc424,vm_smg_accurate_t9_ads_reflex_down
db4f478c261eea5,vm_smg_accurate_t9_ads_reflex_up
6ebdc24f686abc0,vm_smg_accurate_t9_crawl_b
6ebe024f686b28c,vm_smg_accurate_t9_crawl_f
997e2cee6f50ead,vm_smg_accurate_t9_crawl_in
6ebea24f686c38a,vm_smg_accurate_t9_crawl_l
3da82927c8b86f6,vm_smg_accurate_t9_crawl_out
6ebec24f686c6f0,vm_smg_accurate_t9_crawl_r
e518cc23ca59eca,vm_smg_accurate_t9_fire
63a0cc67655477b,vm_smg_accurate_t9_fire_ads
272e2868ded9e7f,vm_smg_accurate_t9_first_raise
f9a04855080b28c,vm_smg_accurate_t9_gunbutt_swipe
b096e3f0801bc80,vm_smg_accurate_t9_idle
1e0889a32802c6a,vm_smg_accurate_t9_inspect
d6ccee126e1503f,vm_smg_accurate_t9_pullout
a23994567b33f67,vm_smg_accurate_t9_pullout_quick
4b425928a19414d,vm_smg_accurate_t9_putaway
249b8e5713f20d9,vm_smg_accurate_t9_putaway_quick
47cb9a5e4d5cf2b,vm_smg_accurate_t9_reload
a18565452d907ed,vm_smg_accurate_t9_reload_empty
69a419e29410e44,vm_smg_accurate_t9_reload_mixclip
1263aec47048bad,vm_smg_accurate_t9_reload_mixclip_ads
22cf52df458a1c8,vm_smg_accurate_t9_sprint_in
e68be1bb310999,vm_smg_accurate_t9_sprint_loop
cebb1163ce7646d,vm_smg_accurate_t9_sprint_out
9ec822875b2888,vm_smg_accurate_t9_sprint_pullout
5888966ed8d782,vm_smg_accurate_t9_sprint_putaway
973e15edce7cae5,vm_smg_accurate_t9_swim_uw_pullout
991b0e65ad8159b,vm_smg_accurate_t9_swim_uw_putaway
492bb4d0d9a8fda,vm_ar_mobility_t9_active_idle
8637d14a79e2149,vm_ar_mobility_t9_reload_empty_mixclip
80d33044cf4c5a3,vm_ar_mobility_t9_reload_mixclip
4fdae7320ef5ab,vm_ar_accurate_t9_inspect_grip
1122b4f75e1bb93,vm_ar_fastfire_t9_inspect_grip
d9fa29a79b55c3c,vm_ar_standard_t9_reload_fastmag_empty
cf8418e1b4a5e35,vm_ar_standard_t9_reload_fastmag_empty_ads
5b9a204cab1a8b1,vm_tr_damagesemi_t9_inspect_grip
27f96c59a85afc,vm_tr_precisionsemi_t9_inspect_grip
7a82d3b45b0b7d7,vm_tr_fastburst_t9_reload_ads
e18086ba4e5b191,vm_tr_fastburst_t9_reload_empty_ads
922dda32d9e046d,vm_ar_damage_t9_reload_ads
26a24f438ff40ac,vm_smg_heavy_t9_inspect_grip
1e156b5e5ff1e1,vm_smg_burst_t9_active_idle
80c5cd9c84d6a68,vm_smg_burst_t9_reload_empty_mixclip
483c5dee8343c41,vm_smg_burst_t9_reload_empty_mixclip_ads
f4fdfb95f854e9a,vm_smg_burst_t9_reload_mixclip
d7a875d15a32b8b,vm_smg_burst_t9_reload_mixclip_ads
56fae9a673efd1e,vm_smg_accurate_t9_reload_ads
e9527ace160ee50,vm_smg_accurate_t9_reload_empty_ads
8f820bca95c6a3e,vm_pistol_fullauto_t9_reload_ads
be100314a9100b0,vm_pistol_fullauto_t9_reload_empty_ads
2c7ba83e3bbc50d,vm_shotgun_semiauto_t9_idle_active
84f0a8a03cd3b83,vm_shotgun_pump_t9_ads_optics_fire
2452808ad3e34f7,vm_sledgehammer_t9_idle_active
6aed9518f649342,vm_wakizashi_t9_active_idle
31c2a3dea1634ef,vm_baseball_bat_t9_idle_active
79c5627a7ebe3aa,vm_smoke_grenade_t9_cancel
5a0cd560c765de6,vm_smoke_grenade_t9_pullpin
878c0dd04e34e15,vm_frag_grenade_t9_cancel
1c5b72a3601a17b,vm_frag_grenade_t9_pullpin
5d334eb5a619ddd,vm_concussion_grenade_t9_cancel
68b01f5ee332c33,vm_concussion_grenade_t9_pullpin
647613ffdacb0f1,vm_semtex_grenade_t9_cancel
6c34221a7aef527,vm_semtex_grenade_t9_pullpin
d5394298ef56819,vm_hatchet_t9_cancel
8b625119c57bcbf,vm_hatchet_t9_pullpin

**Comment by EthanC** [comment]
Thanks
