### ISSUE TITLE
Season Four Operators (Hash Verified)

### ISSUE THREAD

**Issue by ItsNatoriousB** [Scobalula/GreyhoundPackageIndex#72]
b34bf1e1bcfb998,c_t9_sa_pl_deathstalker_head
6ba5966ef5a4e89,c_t9_sa_pl_deathstalker_arms
be1e0f1b37d4173,c_t9_sa_pl_deathstalker_arms_viewbody
cb6a59b2caab3db,c_t9_sa_pl_deathstalker_lowerbody
df6b08ffcf3dc25,c_t9_sa_pl_deathstalker_lowerbody_viewbody
73c03959e6b620d,c_t9_sa_pl_deathstalker_torso
a4504699991255f,c_t9_sa_pl_deathstalker_torso_viewbody
59cd16ce05e6ff4,c_t9_sa_pl_deathstalker_viewarms
470b412cbaa79fe,c_t9_sa_pl_deathstalker_viewlegs
f29327b100e7fae,c_t9_sa_pl_deathstalker_snake
e422fd3798ad150,c_t9_sa_pl_deathstalker_snake_arms
faf0af611f0080c,c_t9_sa_pl_deathstalker_snake_arms_viewbody
881ea1bd627b359,c_t9_sa_pl_deathstalker_snake_head
ddc2577f6a3ec1c,c_t9_sa_pl_deathstalker_snake_lowerbody
df31c14313a6fa0,c_t9_sa_pl_deathstalker_snake_lowerbody_viewbody
a3ef4700571179e,c_t9_sa_pl_deathstalker_snake_torso
9a757fdcb77a96a,c_t9_sa_pl_deathstalker_snake_torso_viewbody
a204d017df69521,c_t9_sa_pl_deathstalker_snake_viewarms
508e21a1a4d60b3,c_t9_sa_pl_deathstalker_snake_viewlegs
ca76ca7db02b6c0,c_t9_usa_pl_adler_buoy_arms
d7c5bf64aefbb5c,c_t9_usa_pl_adler_buoy_arms_viewbody
44426ef9cc9ebc9,c_t9_usa_pl_adler_buoy_head
caed09b90559a4c,c_t9_usa_pl_adler_buoy_lowerbody
a50041d6199d030,c_t9_usa_pl_adler_buoy_lowerbody_viewbody
d6138e4b65e52ce,c_t9_usa_pl_adler_buoy_torso
59fd1c5725664fa,c_t9_usa_pl_adler_buoy_torso_viewbody
4cd08f03851a011,c_t9_usa_pl_adler_buoy_viewarms
a877e0837aab603,c_t9_usa_pl_adler_buoy_viewlegs
8eafa2ac4a96daa,c_t9_uk_pl_mi6_derby_arms
6ed9b17e47d2a7e,c_t9_uk_pl_mi6_derby_arms_viewbody
f2c3b4358645a6b,c_t9_uk_pl_mi6_derby_arms_viewbody_ms
ed04b43581616ee,c_t9_uk_pl_mi6_derby_arms_viewbody_pc
ec63143580d963b,c_t9_uk_pl_mi6_derby_arms_viewbody_sy
360fbeff9a93f1b,c_t9_uk_pl_mi6_derby_head
cc6198a0f2ef636,c_t9_uk_pl_mi6_derby_lowerbody
3084deb3e241092,c_t9_uk_pl_mi6_derby_lowerbody_viewbody
d7b11039a460c3c,c_t9_uk_pl_mi6_derby_torso
28b3aacd59ca000,c_t9_uk_pl_mi6_derby_torso_viewbody
331344a5b4fbffb,c_t9_uk_pl_mi6_derby_viewarms
37327f7e461d3e3,c_t9_uk_pl_mi6_football_arms
23605fdb002165d,c_t9_uk_pl_mi6_football_arms_viewbody
c2c55af25d37c3a,c_t9_uk_pl_mi6_football_head
ed960df3b0b15ed,c_t9_uk_pl_mi6_football_lowerbody
5b4cf102221247f,c_t9_uk_pl_mi6_football_lowerbody_viewbody
b81a554058d2013,c_t9_uk_pl_mi6_football_torso
da7e9f73d50382d,c_t9_uk_pl_mi6_football_torso_viewbody
c873a4c16de0e8e,c_t9_uk_pl_mi6_football_viewarms
78be9347c9fb5c8,c_t9_uk_pl_mi6_football_viewlegs
d0266ffa92b0614,c_t9_uk_pl_mi6_uncharted_arms
13b51c76f527048,c_t9_uk_pl_mi6_uncharted_arms_viewbody
1bec0c452150ae5,c_t9_uk_pl_mi6_uncharted_head
db5a43ce440d2d0,c_t9_uk_pl_mi6_uncharted_lowerbody
1d7712ec9e3248c,c_t9_uk_pl_mi6_uncharted_lowerbody_viewbody
a7fe91af8f79f3a,c_t9_uk_pl_mi6_uncharted_torso
33a4927b64d06ee,c_t9_uk_pl_mi6_uncharted_torso_viewbody
1296c529d1ad35d,c_t9_uk_pl_mi6_uncharted_viewarms
5deb9294b4b5dff,c_t9_uk_pl_mi6_uncharted_viewlegs
729dc40939de774,c_t9_usa_pl_navyseal_grunge_arms
c95b366d73bb0e8,c_t9_usa_pl_navyseal_grunge_arms_viewbody
561360a24869745,c_t9_usa_pl_navyseal_grunge_head
333b6107a2f8bb0,c_t9_usa_pl_navyseal_grunge_lowerbody
4918d5f7a8bdbac,c_t9_usa_pl_navyseal_grunge_lowerbody_viewbody
919cebf8fe9931a,c_t9_usa_pl_navyseal_grunge_torso
33deba2d175998e,c_t9_usa_pl_navyseal_grunge_torso_viewbody
91110adfb1f78bd,c_t9_usa_pl_navyseal_grunge_viewarms
dc65d84a950035f,c_t9_usa_pl_navyseal_grunge_viewlegs
646e6303b37629a,c_t9_usa_pl_cia_big_joke_3_arms
b16d7e120a1000e,c_t9_usa_pl_cia_big_joke_3_arms_viewbody
ab2a7f4d27c3e4b,c_t9_usa_pl_cia_big_joke_3_head
63f87f30b763e6,c_t9_usa_pl_cia_big_joke_3_lowerbody
f5c9fe31c486b62,c_t9_usa_pl_cia_big_joke_3_lowerbody_viewbody
7c705dde43ecb6c,c_t9_usa_pl_cia_big_joke_3_torso
b9debf0b0e29d90,c_t9_usa_pl_cia_big_joke_3_torso_viewbody
b6503fb933419ab,c_t9_usa_pl_cia_big_joke_3_viewarms
9eca5551e715f9d,c_t9_usa_pl_cia_big_joke_3_viewlegs

**Comment by EthanC** [comment]
Thanks
