### ISSUE TITLE
CW OTs 9 anims

### ISSUE THREAD

**Issue by pmr360** [Scobalula/GreyhoundPackageIndex#91]
efe340db1208c12,vm_smg_cqb_t9_ads_acog_down
5c0b420424d8857,vm_smg_cqb_t9_ads_acog_up
e80b6ae00ea4ed3,vm_smg_cqb_t9_ads_base_down
3391ff975299592,vm_smg_cqb_t9_ads_base_up
2416e9b0d0cc448,vm_smg_cqb_t9_ads_holo_down
3f80df9878063c1,vm_smg_cqb_t9_ads_holo_up
6a1a0b7d4df6aee,vm_smg_cqb_t9_ads_reddot_down
df691aa042c771b,vm_smg_cqb_t9_ads_reddot_up
e94b395e16babf2,vm_smg_cqb_t9_ads_reflex_down
be0cd7016912637,vm_smg_cqb_t9_ads_reflex_up
ae8c27b5f6bb262,vm_smg_cqb_t9_crawl_b
ae8be7b5f6bab96,vm_smg_cqb_t9_crawl_f
54c85a324141fab,vm_smg_cqb_t9_crawl_in
ae8c47b5f6bb5c8,vm_smg_cqb_t9_crawl_l
3339b3643d95898,vm_smg_cqb_t9_crawl_out
ae8b27b5f6b9732,vm_smg_cqb_t9_crawl_r
4c671749bfc0ac,vm_smg_cqb_t9_fire
89fc97450d71b25,vm_smg_cqb_t9_fire_ads
ec89d4158323a38,vm_smg_cqb_t9_fire_ads_acog
984b0b9bf9579b5,vm_smg_cqb_t9_first_raise
26ff392dc9b723c,vm_smg_cqb_t9_inspect
dc82ff43c2542e9,vm_smg_cqb_t9_pullout
d18a373e5c46885,vm_smg_cqb_t9_pullout_quick
5ee007832c6d547,vm_smg_cqb_t9_putaway
b7c643ae5e3919f,vm_smg_cqb_t9_putaway_quick
d3587098dabd95d,vm_smg_cqb_t9_reload
7e2b44f5317e92b,vm_smg_cqb_t9_reload_empty
998a2fc26357ec5,vm_smg_cqb_t9_reload_ext
75b2e63bc82a243,vm_smg_cqb_t9_reload_ext_empty
ac3bd4a9e54169a,vm_smg_cqb_t9_sprint_in
ee94b293a02d1d7,vm_smg_cqb_t9_sprint_loop
10e77cb24f43c33,vm_smg_cqb_t9_sprint_out
975203b691faf1e,vm_smg_cqb_t9_sprint_pullout
a77619ec69385b0,vm_smg_cqb_t9_sprint_putaway
9087a0b1ad87b9b,vm_smg_cqb_t9_swim_uw_pullout
e4948761bc4ded1,vm_smg_cqb_t9_swim_uw_putaway

**Comment by pmr360** [comment]
82575c9e909b0b3,wpn_t9_zm_mega_barrel_micro_mag_view
13d58eae49a8066,wpn_t9_zm_mega_barrel_micro_mag_world
854443166f26f30,wpn_t9_zm_mega_barrel_pistol_mag_view
6174147b1f1c3cb,wpn_t9_zm_mega_barrel_pistol_mag_world
673bca5ee4cd1b,wpn_t9_zm_mega_barrel_blazer_beam_mag_view
dde73b28a05cc6e,wpn_t9_zm_mega_barrel_blazer_beam_mag_world
4cef0e52ff6a3b3,wpn_t9_zm_mega_barrel_spreadshot_mag_world
f9164cbe9383718,wpn_t9_zm_mega_barrel_spreadshot_mag_view

**Comment by EthanC** [comment]
Thanks for your submission, I've added the XModel hashes from the second comment. I'm going to leave this Issue open until we have another solution for user-generated names as I'm personally not a fan of mixing them with verified hashes.

**Comment by pmr360** [comment]
These are actually the official names haven't uploaded the other ones for the thumper which are not the official ones.
