### ISSUE TITLE
Some more wonder weapon stuff.

### ISSUE THREAD

**Issue by LeftoverAtoms** [Scobalula/GreyhoundPackageIndex#92]
xmodel_2b4ebdb1bd0ed5b,wpn_t9_zm_mega_barrel_blazer_beam_view
xmodel_a85601ea74114ae,wpn_t9_zm_mega_barrel_blazer_beam_world
xmodel_418b053905ac873,wpn_t9_zm_mega_barrel_micro_view
xmodel_1d3192381249b26,wpn_t9_zm_mega_barrel_micro_world
xmodel_9032f99f5519c84,wpn_t9_zm_mega_barrel_pistol_view
xmodel_877ae4e1587a91f,wpn_t9_zm_mega_barrel_pistol_world
xmodel_e1237cb5dd0946c,wpn_t9_zm_mega_barrel_spreadshot_view
xmodel_22e0cb17889f227,wpn_t9_zm_mega_barrel_spreadshot_world

**Comment by EthanC** [comment]
Thanks for your submission. Going forward, please only include the hash, not the `xmodel_` part.

For example:
```
2b4ebdb1bd0ed5b,wpn_t9_zm_mega_barrel_blazer_beam_view
a85601ea74114ae,wpn_t9_zm_mega_barrel_blazer_beam_world
418b053905ac873,wpn_t9_zm_mega_barrel_micro_view
1d3192381249b26,wpn_t9_zm_mega_barrel_micro_world
9032f99f5519c84,wpn_t9_zm_mega_barrel_pistol_view
877ae4e1587a91f,wpn_t9_zm_mega_barrel_pistol_world
e1237cb5dd0946c,wpn_t9_zm_mega_barrel_spreadshot_view
22e0cb17889f227,wpn_t9_zm_mega_barrel_spreadshot_world
```
